### PR TITLE
fix(#3937): respect correct host header

### LINKED ISSUE #3937: dns interceptor doesn't set port in host header
https://github.com/nodejs/undici/blob/503ad7679118530d8ecdf0f202aad298aab4ec47/lib/interceptor/dns.js#L361

I believe this should be using `host` instead of `hostname`... otherwise we will strip the port...

### PR DESCRIPTION
**Pull request by metcoder95**
## This relates to...

Closes #3937

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

File: test/interceptors/dns.js [hunk 1]
```diff
@@ -1731,3 +1731,86 @@ test('Should handle max cached items', async t => {
   t.equal(response3.statusCode, 200)
   t.equal(await response3.body.text(), 'hello world! (x2)')
 })
+
+test('#3937 - Handle host correctly', { only: true }, async t => {
```
Comment (mcollina) [inline test/interceptors/dns.js:1735]:
```suggestion
test('#3937 - Handle host correctly', async t => {
```

**Review by mcollina — APPROVED** [review]
lgtm with a nit
