### PR TITLE
fix(dispatcher): pass socketPath to custom connect callbacks

### LINKED ISSUE #3486: socketPath option is not passed to the connect function
## Bug Description

In `Pool` dispatcher `socketPath` option is not passed to the `connect` if `connect` is a function.

## Reproducible By

```
const dispatcher = new Agent ( {
    socketPath: "/var/run/socket",
    connect ( options, callback ) {
        console.log( options );
        process.exit();
    }
} )

await fetch( "http://local/", {
    dispatcher
} );
```

## Expected Behavior

Expecting to see `socketPath` in options, passed to the `connect` function.

When `connect` is specified as object - it works, but for function you just forget to pass `socketPath`.

### PR DESCRIPTION
**Pull request by theamodhshetty**
## Summary
When `Pool` / `RoundRobinPool` are created with a custom `connect` function, `socketPath` from dispatcher options is currently not forwarded to the connector callback options.

This patch fixes that by:
- preserving `socketPath` in pool options passed down to `Client`
- forwarding `socketPath` in `Client` connector invocation options when present
- updating `buildConnector.Options` typing to include optional `socketPath`
- adding regression tests for both `Pool` and `RoundRobinPool`

Fixes #3486.

## Testing
- `node --test test/pool.js --test-name-pattern "passes socketPath to custom connect function"`
- `node --test test/round-robin-pool.js --test-name-pattern "passes socketPath to custom connect function"`
- `npx tsd --files test/types/connector.test-d.ts`
- `npx eslint lib/core/symbols.js lib/dispatcher/client.js lib/dispatcher/pool.js lib/dispatcher/round-robin-pool.js test/pool.js test/round-robin-pool.js`

### CODE REVIEW

File: lib/dispatcher/client.js [hunk 1]
```diff
@@ -247,6 +248,7 @@ class Client extends DispatcherBase {
     this[kKeepAliveTimeoutValue] = this[kKeepAliveDefaultTimeout]
     this[kServerName] = null
     this[kLocalAddress] = localAddress != null ? localAddress : null
+    this[kSocketPath] = socketPath != null ? socketPath : null
```
Comment (metcoder95) [inline lib/dispatcher/client.js]: any reason of why this is needed?

**Comment by theamodhshetty** [comment]
Good callout, thanks. I pushed a follow-up to remove the symbol/client-instance storage approach.

What I changed:
- no `kSocketPath` usage in `Client` anymore
- when `connect` is a custom function and `socketPath` is provided, `Client` now wraps the custom connector and injects `socketPath` into connector opts
- `connect()` now only passes runtime connection fields (host/port/localAddress/etc.)
- added coverage in `test/client.js` for `socketPath` + custom `connect`

Commit: `32047692`

File: lib/core/symbols.js [hunk 2]
```diff
@@ -19,6 +19,7 @@ module.exports = {
   kBodyTimeout: Symbol('body timeout'),
   kServerName: Symbol('server name'),
   kLocalAddress: Symbol('local address'),
+  kSocketPath: Symbol('socket path'),
```
Comment (metcoder95) [inline lib/core/symbols.js:22]: remove?
