### PR TITLE
fix: remove `authorization` header when redirecting to unknown origins

### LINKED ISSUE #872: `authorization` header is not deleted on redirects to third party origins
## Bug Description

Security flaw.

## Reproducible By

```js
const http = require('http');
const undici = require('undici');

const server = http.createServer((request, response) => {
    if (request.headers.authorization != 'test') {
        response.statusCode = 403;
        response.end();
        return;
    }

    response.statusCode = 302;
    response.setHeader('location', 'https://httpbin.org/anything');
    response.end();
});

server.listen(8080, async () => {
    const {statusCode, headers, body} = await undici.request('http://localhost:8080', {
        maxRedirections: 3,
        headers: {
            authorization: 'test'
        }
    });

    const chunks = [];
    for await (const chunk of body) {
        chunks.push(chunk);
    }

    const parsed = JSON.parse(Buffer.concat(chunks));
    console.log(parsed.headers.Authorization);

    undici.getGlobalDispatcher().destroy();
    server.close();
});
```

## Expected Behavior

The `authorization` header should be deleted when redirecting to third party origin.

## Environment

```
Linux solus 5.13.1-187.current #1 SMP PREEMPT Wed Jul 7 19:52:26 UTC 2021 x86_64 GNU/Linux
Node v16.4.2
undici@4.1.0
```

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #872

### CODE REVIEW

File: lib/handler/redirect.js [hunk 1]
```diff
@@ -119,27 +119,28 @@ function parseLocation (statusCode, headers) {
 }
 
 // https://tools.ietf.org/html/rfc7231#section-6.4.4
-function shouldRemoveHeader (header, removeContent) {
+function shouldRemoveHeader (header, removeContent, unknownOrigin) {
   return (
     (header.length === 4 && header.toString().toLowerCase() === 'host') ||
-    (removeContent && header.toString().toLowerCase().indexOf('content-') === 0)
+    (removeContent && header.toString().toLowerCase().indexOf('content-') === 0) ||
+    (header.length === 13 && header.toString().toLowerCase() === 'authorization' && unknownOrigin)
```
Comment (ronag) [inline lib/handler/redirect.js:126]:
```suggestion
    (unknownOrigin && header.length === 13 && header.toString().toLowerCase() === 'authorization')
```

checking `unknownOrigin` first is faster.

**Review by ronag — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm
