### PR TITLE
fix(http2): preserve accepted streams after GOAWAY

### LINKED ISSUE #5089: Graceful http2 GOAWAY is handled as hard connection failure
## Bug Description

Graceful http2 GOAWAY is handled as hard connection failure

## Reproducible By

```js
import { once } from "node:events";
import { createSecureServer } from "node:http2";
import pem from "@metcoder95/https-pem";
import { Client } from "undici";

const server = createSecureServer(
  await pem.generate({ opts: { keySize: 2048 } }),
);

const seen = [];
let session;

server.on("session", (s) => {
  session = s;
});

server.on("stream", (stream, headers) => {
  seen.push(headers[":path"]);

  stream.respond({ ":status": 200 });

  setTimeout(() => {
    if (!stream.closed) {
      stream.end(`ok:${headers[":path"]}`);
    }
  }, 200);

  if (seen.length === 3) {
    setTimeout(() => {
      session.goaway();
    }, 50);
  }
});

await once(server.listen(0), "listening");

const client = new Client(`https://localhost:${server.address().port}`, {
  pipelining: 10,
  connect: { rejectUnauthorized: false },
});

const results = await Promise.allSettled(
  [1, 2, 3].map((i) =>
    client
      .request({ path: `/${i}`, method: "GET" })
      .then(async (res) => res.body.text()),
  ),
);

console.log("server saw", seen);
console.log(
  results.map((r) => {
    return r.status === "fulfilled"
      ? { status: r.status, value: r.value }
      : { status: r.status, code: r.reason.code, message: r.reason.message };
  }),
);

await client.close();
await new Promise((resolve) => server.close(resolve));
```

Observe that the server receives all 3 requests before `GOAWAY`, but all 3 client requests reject.

## Expected Behavior

A graceful code-0 `GOAWAY` should stop the client from creating new streams on that session, but streams already accepted by the server should still be allowed to finish when they are within `lastStreamID`.

For the repro above, I would expect the 3 in-flight requests to resolve successfully because the server had already accepted them before calling `session.goaway()`.

## Logs & Screenshots

Observed output on this checkout:

```txt
server saw [ '/1', '/2', '/3' ]
[
  {
    status: 'rejected',
    code: 'UND_ERR_SOCKET',
    message: 'HTTP/2: "GOAWAY" frame received with code 0'
  },
  {
    status: 'rejected',
    code: 'UND_ERR_SOCKET',
    message: 'HTTP/2: "GOAWAY" frame received with code 0'
  },
  {
    status: 'rejected',
    code: 'UND_ERR_SOCKET',
    message: 'HTTP/2: "GOAWAY" frame received with code 0'
  }
]
```

## Environment

macOS 26.4.1
Node v24.15.0
undici v8.1.0

### PR DESCRIPTION
**Pull request by trivikr**
## This relates to...

Fixes: https://github.com/nodejs/undici/issues/5089

## Rationale

HTTP/2 `GOAWAY` with `NO_ERROR` should not fail streams the server has already accepted.

This change preserves in-flight accepted streams, retries work beyond `lastStreamID`, and updates the tests to cover the intended graceful shutdown behavior.

## Changes

- Track request stream IDs in the HTTP/2 client
- Treat `GOAWAY` with code `0` as informational rather than a socket failure
- Only retire/requeue requests whose stream IDs are beyond `lastStreamID`
- Allow already-accepted streams to complete normally after `GOAWAY`

### Features

N/A

### Bug Fixes

- Fix handling of HTTP/2 `GOAWAY` so accepted streams are not failed prematurely
- Fix client reconnection behavior after graceful `GOAWAY`

### Breaking Changes and Deprecations

N/A

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md#developers-certificate-of-origin

Assisted-by: openai:gpt-5.4

### CODE REVIEW

File: lib/dispatcher/client-h2.js [hunk 1]
```diff
@@ -698,8 +753,13 @@ function writeH2 (client, request) {
 
   // Track whether we received a response (headers)
   let responseReceived = false
+  const isActiveStream = () => request[kRequestStreamId] === stream.id
 
   stream.once('response', headers => {
+    if (!isActiveStream()) {
+      return
+    }
```
Comment (mcollina) [inline lib/dispatcher/client-h2.js:848]: this should never happen, why is there this guard?

File: lib/dispatcher/client-h2.js [hunk 2]
```diff
@@ -730,18 +790,24 @@ function writeH2 (client, request) {
   })
 
   stream.once('end', () => {
+    if (!isActiveStream()) {
+      return
+    }
```
Comment (mcollina) [inline lib/dispatcher/client-h2.js]: ditto

**Review by mcollina — CHANGES_REQUESTED** [review]

File: lib/dispatcher/client-h2.js (hunk 1 above)
Comment (trivikr) [reply lib/dispatcher/client-h2.js:848]: Because the same `request` can stop belonging to that particular HTTP/2 `stream` after the listeners are attached.

After `GOAWAY` handling, the requests on streams the server did not accept get `request[kRequestStreamId] = null` so they can be retried on a new session.

The guard is repeated at each handler because each event is independent and can arrive at a different time after the request-to-stream association has changed. A single earlier check would not protect later events.

Both the `#3753` and `#5089` tests hang if we remove this check.

Comment (mcollina) [reply lib/dispatcher/client-h2.js:848]: why aren't we removing the event hanlders then?

File: lib/dispatcher/client-h2.js [hunk 3]
```diff
@@ -311,48 +340,56 @@ function onHttp2SessionEnd () {
...
-  client[kHTTPContext] = null
+  for (let i = pendingIdx; i < previousPendingIdx; i++) {
+    const request = client[kQueue][i]
 
-  // this is an HTTP2 session
-  this.close()
-  this[kHTTP2Session] = null
+    if (request != null) {
+      request[kRequestStreamId] = null
+    }
```
Comment (metcoder95) [inline lib/dispatcher/client-h2.js:411]: Following @mcollina point, maybe we can fully detach the `stream` events at this points; maybe keep a reference of the `stream` itself to the `request` to cleanup upon gracefull shutdown

File: lib/dispatcher/client-h2.js (hunk 1 above)
Comment (trivikr) [reply lib/dispatcher/client-h2.js:848]: The function `removeRequestStreamListeners` was added in https://github.com/nodejs/undici/pull/5090/changes/a896f6a955f6c02b05a20362d788dfa75fbd612a

File: lib/dispatcher/client-h2.js (hunk 2 above)
Comment (trivikr) [reply lib/dispatcher/client-h2.js]: The function `removeRequestStreamListeners` was added in https://github.com/nodejs/undici/pull/5090/changes/a896f6a955f6c02b05a20362d788dfa75fbd612a

File: lib/dispatcher/client-h2.js (hunk 3 above)
Comment (trivikr) [reply lib/dispatcher/client-h2.js:411]: The function `clearRequestStream` was added in https://github.com/nodejs/undici/pull/5090/changes/a896f6a955f6c02b05a20362d788dfa75fbd612a

**Review by mcollina — APPROVED** [review]
lgtm

**Review by metcoder95 — APPROVED** [review]
great work! lgtm
