### PR TITLE
fix(interceptor): preserve tuple headers in dns interceptor

### LINKED ISSUE #4444: DNS interceptor breaks headers of type `[string, string][]`
## Bug Description

Unable to use headers of type `[string, string][]`, using `Record<string, string>` works (see below).

## Reproducible By

```js
import http from "node:http";
import { Agent, interceptors, request } from "undici";

const port = process.env.PORT ?? 3001;

const { cache, dns } = interceptors;

const good = new Agent().compose(cache());

const fail = new Agent().compose(cache(), dns());

http
  .createServer((req, res) => {
    console.log(req.headers);
    res.end();
  })
  .listen(port, async () => {
    const headers = [["foo", "bar"]];

    await request(`http://localhost:${port}`, {
      dispatcher: good,
      headers,
    });

    await request(`http://localhost:${port}`, {
      dispatcher: fail,
      headers,
    });

    const headersAsRecord = { foo: "bar" };
    await request(`http://localhost:${port}`, {
      dispatcher: fail,
      headers: headersAsRecord,
    });
  });
```

```
node index.js
{ host: 'localhost:3001', connection: 'keep-alive', foo: 'bar' }
{ '0': 'foo, bar', host: 'localhost:3001', connection: 'keep-alive' }
{ host: 'localhost:3001', connection: 'keep-alive', foo: 'bar' }
```

### PR DESCRIPTION
**Pull request by theamodhshetty**
## Summary
- preserve non-object header shapes when the dns interceptor injects the host header
- normalize tuple/iterable header inputs into flat key/value arrays before redispatching
- apply the same host-header handling on DNS fallback retries (other IP family)

## Why
`interceptors.dns()` currently rewrites headers with object spread. For tuple-style headers (for example `[ ['foo', 'bar'] ]`) this can produce malformed headers (`'0': 'foo, bar'`) and break requests in composed interceptor flows.

## Tests
- added `#4444 - Should preserve tuple-style headers` in `test/interceptors/dns.js`
- `node --test test/interceptors/dns.js`
- `npm run lint`

Fixes #4444

### CODE REVIEW

File: lib/interceptor/dns.js [hunk 1]
```diff
@@ -5,6 +5,100 @@ const DecoratorHandler = require('../handler/decorator-handler')
...
+        normalized.push(header[0], header[1])
+      } else {
+        normalized.push(header)
+      }
+    }
+
+    return normalized
+  }
+
+  if (typeof headers === 'object' && typeof headers[Symbol.iterator] === 'function') {
```
Comment (metcoder95) [inline lib/interceptor/dns.js]: I'd suggest to wait a bit until the changes from this PR are added so we can enhance the iterator check: https://github.com/nodejs/undici/pull/4824/changes#diff-e0a4e92ad66667607d700021123bf26260711f87fda60b44f6867a3f22087410R338

Comment (theamodhshetty) [reply lib/interceptor/dns.js]: Good point, thanks. I removed the generic iterable normalization from this PR and kept the fix scoped to array/object header shapes for now. Once #4824 lands, I can follow up with the safer iterator handling path.

Comment (mcollina) [reply lib/interceptor/dns.js]: I've landed that

Comment (theamodhshetty) [reply lib/interceptor/dns.js]: Picked this up in `bee4c1c`. I kept the tuple-header fix and extended the normalization path to treat safe iterables the same way, so `Map`/`Headers` style inputs survive the DNS host injection too. I also added a DNS interceptor regression for iterable headers and rechecked the behavior with a direct request round-trip locally.
