### PR TITLE
fix: undici stream throwOnError

### LINKED ISSUE #1753: undici.stream ignores throwOnError
## Bug Description

`undici.stream`/`Dispatcher.stream` accepts [`RequestOptions`](https://undici.nodejs.org/#/docs/api/Dispatcher?id=parameter-requestoptions) which extends [`DispatchOptions`](https://undici.nodejs.org/#/docs/api/Dispatcher?id=parameter-dispatchoptions) which includes `throwOnError` to throw on 4xx and 5xx HTTP errors, but completely ignores it and calls the factory regardless of the status code.

## Reproducible By

```js
import fs from "node:fs";
import undici from "undici";

await undici.stream(
  "https://httpbin.org/status/502",
  { throwOnError: true },
  () => fs.createWriteStream("httpbin_502.txt")
);
```

Successfully creates an empty `httpbin_502.txt` (because httpbin.org sends empty body on `/status`)

## Expected Behavior

```
ResponseStatusCodeError: Response status code 502: BAD GATEWAY
```

### Additional context

* `throwOnError` was introduced in https://github.com/nodejs/undici/pull/1453
* the current code for `request`: https://github.com/nodejs/undici/blob/0a7ba7226ce8cdd6bc67527bcd3427665ff7edd2/lib/api/api-request.js#L95
* `stream` lacks that code: https://github.com/nodejs/undici/blob/0a7ba7226ce8cdd6bc67527bcd3427665ff7edd2/lib/api/api-stream.js#L92

### PR DESCRIPTION
**Pull request by dancastillo**
undici.stream throwOnError fixes #1753

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ronag** [comment]
Wait with landing this.

File: lib/api/api-stream.js [hunk 1]
```diff
@@ -96,6 +97,24 @@ class StreamHandler extends AsyncResource {
...
 
+    if (this.throwOnError && statusCode >= 400) {
+      const headers = this.responseHeaders === 'raw' ? util.parseRawHeaders(rawHeaders) : util.parseHeaders(rawHeaders)
+      const chunks = []
+      const pass = new PassThrough()
+      pass
+        .on('data', (chunk) => chunks.push(chunk))
+        .on('end', () => {
+          const payload = Buffer.concat(chunks).toString('utf8')
+          this.runInAsyncScope(
```
Comment (ronag) [inline lib/api/api-stream.js:108]: This won't work since `getResolveErrorBodyCallback` expects a `BodyReadable`.

**Review by ronag — CHANGES_REQUESTED** [review]
`getResolveErrorBodyCallback` needs to be rewritten to work without the `body` parameter. Also, seems to be missing tests as the current broken implementation seems to pass?

File: lib/api/api-stream.js (hunk 1 above)
Comment (ronag) [reply lib/api/api-stream.js:108]: Should also automatically parse json like request does.

File: lib/core/util.js [hunk 2]
```diff
@@ -342,6 +342,38 @@ function getSocketInfo (socket) {
   }
 }
 
+async function getResolveErrorBodyCallback ({ callback, body, contentType, statusCode, statusMessage, headers, payload }) {
+  if (typeof payload === 'string' && statusCode >= 400) {
+    process.nextTick(callback, new ResponseStatusCodeError(`Response status code ${statusCode}${statusMessage ? `: ${statusMessage}` : ''}`, statusCode, headers, payload))
+    return
+  }
```
Comment (ronag) [inline lib/core/util.js:349]: This shouldn't be necessary.

File: test/client-stream.js [hunk 3]
```diff
@@ -785,4 +785,38 @@ test('stream legacy needDrain', (t) => {
...
+      t.teardown(client.close.bind(client))
+
+      client.stream({
+        path: '/',
+        method: 'GET',
+        throwOnError: true,
+        opaque: new PassThrough()
+      }, ({ opaque: pt }) => {
+        pt.on('data', () => {
+          t.not.pass()
```
Comment (KhafraDev) [inline test/client-stream.js:812]: I don't think this is a thing, the equivalent being t.fail.

Comment (dancastillo) [reply test/client-stream.js]: updated to `t.fail()`

**Comment by dancastillo** [comment]
@ronag @KhafraDev addressed changes ptal

**Review by KhafraDev — APPROVED** [review]

File: lib/api/api-stream.js [hunk 4]
```diff
@@ -96,6 +98,29 @@ class StreamHandler extends AsyncResource {
...
+            callback,
+            null,
+            new ResponseStatusCodeError(
+              `Response status code ${statusCode}${statusMessage ? `: ${statusMessage}` : ''}`,
+              statusCode,
+              headers,
+              payload
+            )
+          )
+        })
```
Comment (ronag) [inline lib/api/api-stream.js:119]: Needs to handle error event

**Review by ronag — CHANGES_REQUESTED** [review]

**Comment by dancastillo** [comment]
@ronag added error event handling ptal
