### PR TITLE
Fix `blob.type` not having the response type

### LINKED ISSUE #925: Blob should have response content type
Body mixin in `undici.request` and `undici.fetch` when returning a `Blob` should also set `Blob.type` to the corresponding `content-type` header from the response.

Search for `new Body` and you should pass in a `type` in `new Blob(chunks, { type: headers['content-type'] })`.

Don't forget tests.

### PR DESCRIPTION
**Pull request by MSE99**
#### Description

Closes #925 

Sets the `type` property in `Blob` objects, to the value found in `content-type` response header.

### CODE REVIEW

File: lib/api/api-request.js [hunk 1]
```diff
@@ -71,14 +71,15 @@ class RequestHandler extends AsyncResource {
       return
     }
 
-    const body = new Readable(resume, abort)
+    const parsedHeaders = util.parseHeaders(headers)
```
Comment (ronag) [inline lib/api/api-request.js:74]: This is slow. Can you do this lazily in the blob getter?

**Review by ronag — APPROVED** [review]
Nice!

**Comment by ronag** [comment]
Tests are failing. That needs to be fixed.

File: test/client-request.js [hunk 2]
```diff
@@ -228,6 +228,31 @@ test('request text', (t) => {
   })
 })
 
+test('request blob', (t) => {
```
Comment (ronag) [inline test/client-request.js:231]: 'should set type of blob object to the value of the `Content-Type` header from response'
