### PR TITLE
Fix array headers

### LINKED ISSUE #1532: Mocking header set-cookie issue
Hi,
There is a issue with mocking header set-cookie and when i try mocking multiple set-cookie

Example: When i mock request
```
mockAgent.get(accountFrontHost).intercept({
            path: '/user/login',
            method: 'POST',
            body: JSON.stringify(expectedPostUserLoginBody),
            query: expectedPostUserLoginParams,
            headers: {'Accept-Version': '1.0.0', 'Content-Type': 'application/json'}
        }).reply(204, {},{
            headers: {
                'set-cookie': [
                    'aaaaaaaa=bbbbbbbbbbbbbbbbbb; Domain=.example.pl; Path=/; Expires=Fri, 07 Jul 2023 10:04:22 GMT; HttpOnly; Secure; SameSite=None',
                    'cccccccc=dddddddddddddddddd; Domain=.example.pl; Path=/; Expires=Fri, 07 Jul 2023 10:04:22 GMT; HttpOnly; Secure',
                    'eeeeeeeeeee=ffffffffffffffff; Domain=.example.pl; Path=/; Expires=Fri, 07 Jul 2023 10:04:22 GMT; HttpOnly; Secure; SameSite=None'
                ]
        }});
```

Mock "flattens" the set-cookie and reply as string not as array of strings

```
statusCode: 204,
  headers: {
    'set-cookie': 'aaaaaaaa=bbbbbbbbbbbbbbbbbb; Domain=.example.pl; Path=/; Expires=Fri, 07 Jul 2023 10:04:22 GMT; HttpOnly; Secure; SameSite=None,cccccccc=dddddddddddddddddd; Domain=.example.pl; Path=/; Expires=Fri, 07 Jul 2023 10:04:22 GMT; HttpOnly; Secure,eeeeeeeeeee=ffffffffffffffff; Domain=.example.pl; Path=/; Expires=Fri, 07 Jul 2023 10:04:22 GMT; HttpOnly; Secure; SameSite=None'
  },

```

### PR DESCRIPTION
**Pull request by mateonunez**
This PR fixes #1532.

The `parseHeaders` method doesn't handle the possibility of the array as the value in the headers. So I've added 1 check to prevent array serialization. I've added 2 tests for that.

The response now is:

```js
{
  statusCode: 200,
  headers: {
    'set-cookie': ['a=b', 'c=d', 'd=e'];
  }
}
```

### CODE REVIEW

File: test/mock-agent.js [hunk 1]
```diff
@@ -2494,3 +2494,30 @@ test('MockAgent - headers in mock dispatcher intercept should be case-insensitiv
 
   t.end()
 })
+
+test('MockAgent - headers should be array of strings', { skip: nodeMajor < 16 }, async (t) => {
```
Comment (mcollina) [inline test/mock-agent.js:2498]: why skip is Node is < 16?

Comment (mateonunez) [reply test/mock-agent.js:2498]: just an oversight, not necessary to skip it

**Review by mcollina — APPROVED** [review]
lgtm
