### PR TITLE
fix: prevent AbortController GC when redirect is 'error'

### LINKED ISSUE #4627: SSE connection may leak when fetch init.redirect = 'error'
## Bug Description

Fetch abort may not take effect when fetch init.redirect = 'error' and this causes SSE connection leak

## Reproducible By
SSE Server:
```
const express = require('express');
const app = express();
const PORT = 3000;

class SSEServer {
  constructor() {
    this.clients = new Set();
  }

  // 添加客户端
  addClient(res) {
    this.clients.add(res);
    
    // 设置 SSE 头
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
      'Access-Control-Allow-Origin': '*'
    });

    // 发送欢迎消息
    this.sendToClient(res, 'connected', { message: 'Welcome to SSE server' });

    // 客户端断开时清理
    res.on('close', () => {
      this.clients.delete(res);
      console.log('Client disconnected. Total clients:', this.clients.size);
    });
  }

  // 向单个客户端发送消息
  sendToClient(res, event, data) {
    res.write(`event: ${event}\n`);
    res.write(`data: ${JSON.stringify(data)}\n\n`);
  }

  // 向所有客户端广播消息
  broadcast(event, data) {
    this.clients.forEach(client => {
      this.sendToClient(client, event, data);
    });
  }

  // 获取客户端数量
  getClientCount() {
    return this.clients.size;
  }
}

// 创建 SSE 服务器实例
const sseServer = new SSEServer();

// 中间件
app.use(express.json());
app.use(express.static('public'));

// SSE 端点
app.get('/sse', (req, res) => {
  sseServer.addClient(res);
  console.log('New client connected. Total clients:', sseServer.getClientCount());
});

// 手动触发事件端点（可选）
app.post('/send-message', (req, res) => {
  const { message } = req.body;
  sseServer.broadcast('custom-message', {
    message: message || 'Manual broadcast',
    timestamp: new Date().toISOString()
  });
  res.json({ success: true, clients: sseServer.getClientCount() });
});

// 启动定时广播
let eventCount = 1;
setInterval(() => {
  const eventData = {
    id: eventCount,
    timestamp: new Date().toISOString(),
    message: `Automatic event #${eventCount}`,
    random: Math.random().toFixed(4),
    clients: sseServer.getClientCount()
  };
  
  sseServer.broadcast('message', eventData);
  console.log(`Broadcasted event ${eventCount} to ${sseServer.getClientCount()} clients`);
  eventCount++;
}, 2000);

app.listen(PORT, () => {
  console.log(`Advanced SSE server running at http://localhost:${PORT}`);
});
```
test
```
import { EventSource } from 'eventsource'
import { fetch } from 'undici'
import { randomUUID } from 'crypto';
setInterval(() => {
    const es = new EventSource('http://127.0.0.1:3000/sse',
        {
            fetch: (url, init) => {
                init.redirect = 'error';
                return fetch(url, init);
            },
        }
    )
    es._id = randomUUID()
    es.onmessage = (event) => {
        if (es.readyState === 2) {
            console.log(es._id, es.readyState, 'receive data after closed!!!!!!!!!!!!!!!')
        }
    };

    setTimeout(() => {
        es.close();
    }, 5000);
}, 1000);
```

## Expected Behavior

SSE connection should be closed properly after fetch abort

## Logs & Screenshots

Image

I edit the source code and add code: console.log('requestFinalizer execute'), so the reason may be that the abortController ac was garbage collected too early.
Image

why use a copy or clone when redirect is not error？
Image

## Environment
Node v20.19.2
undici 7.16.0

### PR DESCRIPTION
**Pull request by mcollina**
## Summary

Fixes #4627

When `fetch()` is called with `redirect: 'error'`, the `requestObject` (the `Request` instance) could be garbage collected while the fetch was still in progress. The `requestObject` holds an internal `AbortController` via the `kAbortController` property. When `requestObject` was GC'd, the `AbortController` was also collected, triggering a `FinalizationRegistry` callback that removed the abort listener from the user's signal. This caused abort signals to have no effect, resulting in connection leaks for SSE streams.

## Changes

The fix stores a reference to `requestObject` in `fetchParams`, which stays alive for the entire duration of the fetch operation. This prevents premature garbage collection of the `requestObject` and its internal `AbortController`.

- Pass `requestObject` to the `fetching()` function
- Add `requestObject` parameter to `fetching()` function signature
- Include `requestObject` in `fetchParams` object

## Test Plan

- Added regression test `test/fetch/issue-4627.js` that requires `--expose-gc` flag
- Test creates an SSE-like streaming server, fetches with `redirect: 'error'`, triggers GC, aborts, and verifies no data is received after abort
- Both tests pass:
  - `abort should work with redirect: error` ✅
  - `abort should work without redirect: error (control test)` ✅

### CODE REVIEW

File: lib/web/fetch/index.js [hunk 1]
```diff
@@ -430,7 +434,10 @@ function fetching ({
     processResponseConsumeBody,
     processResponseEndOfBody,
     taskDestination,
-    crossOriginIsolatedCapability
+    crossOriginIsolatedCapability,
+    // Keep requestObject alive to prevent its AbortController from being GC'd
+    // See https://github.com/nodejs/undici/issues/4627
```
Comment (Uzlopak) [inline lib/web/fetch/index.js]:
```suggestion
```

I would remove this line as it is just a "diary entry". The corresponding test is having the link and is totally fine.
