### PR TITLE
fix: HTTPToken check

### LINKED ISSUE #2409: Non-HTTPToken characters can be used in header names
## Bug Description

The following character `"(),/:;<=>?@[\]{}` is not allowed in the specification, but is allowed in Undici.

References:
<https://fetch.spec.whatwg.org/#header-name>
<https://tools.ietf.org/html/rfc7230#section-3.2.6>
<https://tools.ietf.org/html/rfc9110#section-5.6.2>

## Reproducible By

There is a simple test.

```js
// test.js
function pass(name) {
    try {
        return !!new Headers({ [name]: "test" });
    } catch (e) {
        return false;
    }
}

function assert(cond, message) {
    if (!cond) console.error(message);
}

function test() {
    for (const char of `"(),/:;<=>?@[\\]{}`.split("")) {
        assert(!pass(char), `The string \`${char}\` should throw an error.`);
    }
}

test();
```

## Expected Behavior

The above test should succeed.

## Logs & Screenshots

```sh
> $ node test.js
The string `"` should throw an error.
The string `(` should throw an error.
The string `)` should throw an error.
The string `,` should throw an error.
The string `/` should throw an error.
The string `:` should throw an error.
The string `;` should throw an error.
The string `<` should throw an error.
The string `=` should throw an error.
The string `>` should throw an error.
The string `?` should throw an error.
The string `@` should throw an error.
The string `[` should throw an error.
The string `\` should throw an error.
The string `]` should throw an error.
The string `{` should throw an error.
The string `}` should throw an error.
```

## Environment

Windows 11
Node.js v21.1.0
Undici v5.27.2

### Additional context

None

### PR DESCRIPTION
**Pull request by tsctx**
## This relates to...

Fixes #2409 

### Features

N/A

### Bug Fixes

#2409 

### Breaking Changes and Deprecations

N/A

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by metcoder95 — COMMENTED** [review]
The changes affect `fetch` only, but I wonder if we want to extend it to `undici` itself.

File: lib/fetch/util.js [hunk 1]
```diff
@@ -103,52 +103,57 @@ function isValidReasonPhrase (statusText) {
...
 }
 
-// See RFC 7230, Section 3.2.6.
-// https://github.com/chromium/chromium/blob/d7da0240cae77824d1eda25745c4022757499131/third_party/blink/renderer/platform/network/http_parsers.cc#L321
+/**
+ * @param {string} characters
+ */
 function isValidHTTPToken (characters) {
-  if (!characters || typeof characters !== 'string') {
+  if (characters.length === 0) {
```
Comment (ronag) [inline lib/fetch/util.js:141]: What's the point of this change?

**Comment by tsctx** [comment]
@metcoder95 
Do you mean checking all append headers?

File: lib/fetch/util.js (hunk 1 above)
Comment (tsctx) [reply lib/fetch/util.js:141]: If the length of the empty string was checked explicitly, it would make it easier to understand.
Also, The string check was removed because only `isValidHeaderName` was used.

Comment (tsctx) [reply lib/fetch/util.js:141]: Since it is called after being stringified, I don't think there is a problem.

File: lib/fetch/index.js [hunk 2]
```diff
@@ -2002,7 +2003,7 @@ async function httpNetworkFetch (
                 location = val
               }
 
-              headers.append(key, val)
+              if (isValidHeaderName(key)) headers.append(key, val)
```
Comment (KhafraDev) [inline lib/fetch/index.js:2006]: are these headers expected to be ignored, or should an error be thrown? It doesn't make sense to double validate every header we receive.

File: lib/fetch/index.js [hunk 3]
```diff
@@ -2016,7 +2017,7 @@ async function httpNetworkFetch (
...
```
Comment (KhafraDev) [inline lib/fetch/index.js:2020]: same here

File: lib/fetch/util.js [hunk 4]
```diff
@@ -103,52 +103,57 @@ function isValidReasonPhrase (statusText) {
...
-    c === '?' ||
-    c === '=' ||
-    c === '{' ||
-    c === '}'
-  )
+/**
+ * @see https://tools.ietf.org/html/rfc7230#section-3.2.6
+ * @param {number} c
+ */
+function isTokenCharCode (c) {
```
Comment (KhafraDev) [inline lib/fetch/util.js:110]: this seems to be the only required change here (since the issue seems to be comparing the char code to the actual characters would always return false). I'd prefer if the old checks were added back and only this change made.

File: lib/fetch/index.js (hunk 2 above)
Comment (tsctx) [reply lib/fetch/index.js:2006]: I too think double checking is useless.
If `:status` is passed as an example of an http2 header, the http2 test fails.
I will comment the solution later.

Comment (tsctx) [reply lib/fetch/index.js:2006]: Some solutions,
- Change core so that http2 headers, e.g. `:status`, are not passed.
- Use try-catch.
- Check only the leading colon.

File: lib/fetch/index.js (hunk 3 above)
Comment (tsctx) [reply lib/fetch/index.js:2020]: Explained in the comment above.

File: lib/fetch/index.js (hunk 2 above)
Comment (metcoder95) [reply lib/fetch/index.js:2006]: None of the specific `h2` headers should be passed as those are automatically appended upon request. Although it can be passed, they are going to be overwritten.
On Chrome, `fetch` throws when trying to append them as headers

Comment (tsctx) [reply lib/fetch/index.js:2006]: @metcoder95
Is it correct to identify pseudo-headers with a leading colon and not pass them to Headers#append?
Or change the core?

Comment (tsctx) [reply lib/fetch/index.js:2006]: Probably due to the :status pseudo-header.

Comment (tsctx) [reply lib/fetch/index.js:2006]: Probably due to the `:status` pseudo-header.

Comment (tsctx) [reply lib/fetch/index.js:2006]: The pseudo-header `:status` seems to be the cause

Comment (KhafraDev) [reply lib/fetch/index.js:2006]: please undo both of these changes, we can reevaluate in a dedicated issue

Comment (tsctx) [reply lib/fetch/index.js:2006]: Sure, changes will be undone.

**Review by metcoder95 — APPROVED** [review]
LGTM

File: lib/fetch/util.js (hunk 4 above)
Comment (KhafraDev) [reply lib/fetch/util.js:110]: @tsctx I don't believe this should be blocked by anything. The handling of pseudo-headers has nothing to do with the original issue that this fixes, right?

Comment (tsctx) [reply lib/fetch/util.js:110]: @KhafraDev 
This change will fail the H2 test and should wait.

Comment (tsctx) [reply lib/fetch/util.js:110]: But, I understand your thinking.

Comment (KhafraDev) [reply lib/fetch/util.js:110]: The test isn't sound with my understanding of the fetch spec, I think the failing test(s) can be disabled for now.

Comment (KhafraDev) [reply lib/fetch/util.js:110]: I posted more about my understanding of the fetch spec in the linked issue.

Comment (tsctx) [reply lib/fetch/util.js:110]: @KhafraDev 
After the errands are completed, change the failing H2 test to be skipped.

**Comment by tsctx** [comment]
Hi @metcoder95 @KhafraDev,
I've changed it to skip the failed H2 test.
Could you please take a look at it?

**Review by KhafraDev — APPROVED** [review]

**Review by metcoder95 — APPROVED** [review]
