### PR TITLE
fix fd parsing unquoted attribute values

### LINKED ISSUE #4660: Allow form-data name without quotes
## Bug Description

Currently in a multipart form request the following cannot be parsed:

```
--7427efb8-6ce7-4740-9198-d90399842641
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=test

abc
--7427efb8-6ce7-4740-9198-d90399842641--
```

with this error: `TypeError: expected form-data; name=" for content-disposition header`.

This is a valid request though that the C# MultipartFormDataContent also creates.

## Expected Behavior

This request should be handled

### PR DESCRIPTION
**Pull request by KhafraDev**
fixes #4660 

claude did ~half of this PR so be wary

### CODE REVIEW

File: lib/web/fetch/formdata-parser.js [hunk 1]
```diff
@@ -206,6 +204,113 @@ function multipartFormDataParser (input, mimeType) {
...
+      (headerValue[1] !== 0x74 && headerValue[1] !== 0x54) || // t or T
+      (headerValue[2] !== 0x66 && headerValue[2] !== 0x46) || // f or F
+      headerValue[3] !== 0x2d || // -
+      headerValue[4] !== 0x38 // 8
+    ) {
+      throw parsingError('unknown encoding, expected utf-8\'\'')
+    }
+
+    // Skip utf-8'' and decode the rest
+    value = decodeURIComponent(new TextDecoder().decode(headerValue.subarray(7)))
```
Comment (Uzlopak) [inline lib/web/fetch/formdata-parser.js]: cant we cache this TextDecoder?

File: lib/web/fetch/formdata-parser.js [hunk 2]
```diff
@@ -206,6 +204,113 @@ function multipartFormDataParser (input, mimeType) {
...
+
+    if (input[position.position] !== 0x22) {
+      throw parsingError('Closing quote not found')
+    }
+    position.position++ // skip closing quote
+
+    value = new TextDecoder().decode(quotedValue)
+      .replace(/%0A/ig, '\n')
+      .replace(/%0D/ig, '\r')
+      .replace(/%22/g, '"')
```
Comment (Uzlopak) [inline lib/web/fetch/formdata-parser.js]: nasty regex stuff. Cant we cache the decoder and maybe check if the value contains a '%' before running those replacers?

File: lib/web/fetch/formdata-parser.js [hunk 3]
```diff
@@ -493,6 +521,58 @@ function parsingError (cause) {
...
+    char === 0x3d    // +
+  )
+}
+
+/**
+ * token := 1*<any (US-ASCII) CHAR except SPACE, CTLs,
+ *          or tspecials>
+ * @param {number} char
+ */
+function isToken (char) {
```
Comment (Uzlopak) [inline lib/web/fetch/formdata-parser.js:568]: dont we have such a function already?

File: lib/web/fetch/formdata-parser.js (hunk 2 above)
Comment (KhafraDev) [reply lib/web/fetch/formdata-parser.js]: this was copy and pasted from the old code

File: lib/web/fetch/formdata-parser.js (hunk 3 above)
Comment (KhafraDev) [reply lib/web/fetch/formdata-parser.js:568]: not one that's 100% equivalent, if you're talking about the cookie parser one

File: lib/web/fetch/formdata-parser.js [hunk 4]
```diff
@@ -8,11 +8,11 @@ const assert = require('node:assert')
 const { isomorphicDecode } = require('../infra')
 const { utf8DecodeBytes } = require('../../encoding')
 
-const formDataNameBuffer = Buffer.from('form-data; name="')
-const filenameBuffer = Buffer.from('filename')
 const dd = Buffer.from('--')
 const ddcrlf = Buffer.from('--\r\n')
 
+const decoder = new TextDecoder()
```
Comment (mcollina) [inline lib/web/fetch/formdata-parser.js:14]: Why this is global?

File: lib/web/fetch/formdata-parser.js [hunk 5]
```diff
@@ -206,6 +206,113 @@ function multipartFormDataParser (input, mimeType) {
...
+
+    if (input[position.position] !== 0x22) {
+      throw parsingError('Closing quote not found')
+    }
+    position.position++ // skip closing quote
+
+    value = decoder.decode(quotedValue)
+      .replace(/%0A/ig, '\n')
+      .replace(/%0D/ig, '\r')
+      .replace(/%22/g, '"')
```
Comment (mcollina) [inline lib/web/fetch/formdata-parser.js:301]: Can you have Claude optimize this and just do a single loop?

File: lib/web/fetch/formdata-parser.js (hunk 4 above)
Comment (KhafraDev) [reply lib/web/fetch/formdata-parser.js:14]: https://github.com/nodejs/undici/pull/4662#discussion_r2505948012

File: lib/web/fetch/formdata-parser.js (hunk 5 above)
Comment (KhafraDev) [reply lib/web/fetch/formdata-parser.js:301]: this is the same code as before, copied from another function

**Comment by KhafraDev** [comment]
Can we land this...? It's a bug fix. I don't know why I'm being asked to microoptimize everything.

**Comment by KhafraDev** [comment]
this seems to have fixed #4661 as well, great
