### PR TITLE
cache: honour unqualified no-cache response directive

### LINKED ISSUE #4173: Cache prioritises cacheByDefault/max-age over `no-cache` response directive
## Bug Description

When `cacheByDefault` is set, no revalidation occurs for a response which had the `no-cache` directive.

## Reproducible By

```js
const http = require('node:http');

const server = http.createServer((req, res) => {
  console.log('request received');

  req.on('data', () => {});

  req.on('end', () => {
    res.setHeader('cache-control', 'no-cache');
    res.end('OK');

    console.log('Closing server...');
    server.close(() => console.log('Server closed.'));
  });
});

const port = 1234;
server.listen(port, async () => {
  console.log('server listening on port', port);

  const undici = require('undici');

  const dispatcher = new undici.Agent().compose(undici.interceptors.cache({
    cacheByDefault: 1000,
  }));
  
  const res1 = await undici.fetch(`http://localhost:${port}/`, { dispatcher });
  console.log('res1.status:', res1.status);

  await new Promise(resolve => setTimeout(resolve, 200));

  const res2 = await undici.fetch(`http://localhost:${port}/`, { dispatcher });
  console.log('res2.status:', res2.status);
});
```

## Expected Behavior

https://datatracker.ietf.org/doc/html/rfc9111#name-no-cache-2:

> The no-cache response directive, in its unqualified form (without an argument), indicates that the response **MUST NOT** be used to satisfy any other request without forwarding it for validation and receiving a successful response

## Logs & Screenshots

```
server listening on port 1234
request received
Closing server...
Server closed.
res1.status: 200
res2.status: 200
```

## Environment

node: v22.12.0
undici: 7.8.0

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #4173

## This relates to...

* #4173

## Rationale

https://datatracker.ietf.org/doc/html/rfc9111#name-no-cache-2:

> The no-cache response directive, in its unqualified form (without an argument), indicates that the response **MUST NOT** be used to satisfy any other request without forwarding it for validation and receiving a successful response

## Changes

Add additional check of `no-cache` directive of cached response when deciding if it needs revalidation.

### Features

Na?

### Bug Fixes

* #4173

### Breaking Changes and Deprecations

Changes caching behaviour.

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [S] Benchmarked (**optional**)
- [x] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md#developers-certificate-of-origin

### CODE REVIEW

File: test/no-cache.js
Comment (alxndrsn) [inline test/no-cache.js:1]: Maybe this should be included in an existing test file, e.g. `test/interceptors/cache.js`?

Comment (metcoder95) [reply test/no-cache.js:1]: Let's do that

File: test/interceptors/cache.js [hunk 1]
```diff
@@ -128,6 +128,47 @@ describe('Cache Interceptor', () => {
...
+    const body1 = await res1.body.text()
+    strictEqual(body1, 'Request count: 1')
+    strictEqual(requestCount, 1)
+
+    const res2 = await client.request(request)
+    const body2 = await res2.body.text()
+    strictEqual(body2, 'Request count: 2')
+    strictEqual(requestCount, 2)
+
+    await new Promise(resolve => server.close(resolve))
```
Comment (metcoder95) [inline test/interceptors/cache.js:169]: Not needed? It should be addressed by  L140?

Comment (alxndrsn) [reply test/interceptors/cache.js]: Removed

**Review by metcoder95 — APPROVED** [review]

**Review by pimterry — APPROVED** [review]
