### PR TITLE
fix filename* parsing

### LINKED ISSUE #3760: "Failed to parse body as FormData." with filename*=utf-8 content disposition
## Bug Description

When sending a multipart/form-data with a `filename*=utf-8''` (as the MultipartFormDataContent class in C# does for example, or in this example in the RFC: https://datatracker.ietf.org/doc/html/rfc6266#section-5) content disposition it throws a "Failed to parse body as FormData." TypeError.

## Reproducible By

```
const response = new Response([
    '--83d82e0d-9ced-44c0-ac79-4e66a827415b\r\n' +
    'Content-Type: text/plain\r\n' +
    'Content-Disposition: form-data; name="file"; filename*=utf-8\'\'file%20name.txt\r\n' +
    '\r\n' +
    'testabc\r\n' +
    '--83d82e0d-9ced-44c0-ac79-4e66a827415b--\r\n' +
    '\r\n',
  ].join(''), {
    headers: {
      'content-type': 'multipart/form-data; boundary="83d82e0d-9ced-44c0-ac79-4e66a827415b"'
    }
  });

await response.formData()
```

## Expected Behavior

The existance of a `filename*=utf-8` field shouldn't lead to parse failure, it should be used as the filename.

## Logs & Screenshots

```
node:internal/deps/undici/undici:5619
                    throw new TypeError("Failed to parse body as FormData.");
                          ^

TypeError: Failed to parse body as FormData.
    at node:internal/deps/undici/undici:5619:27
    at successSteps (node:internal/deps/undici/undici:5663:27)
    at fullyReadBody (node:internal/deps/undici/undici:4561:9)
    at async consumeBody (node:internal/deps/undici/undici:5672:7)
    at async file:///index.js:15:1
```

## Environment

This bug is NOT present in node v20.12.2, but IS present from node v20.13 and onward.

### Additional context

Workaround: downgrade to node v20.12.2

### PR DESCRIPTION
**Pull request by KhafraDev**
fixes #3760 

also fixes a case where we were too strict by disallowing spaces after `filename` and `filename*` parameters. The RFC uses examples with spaces ([`filename*= UTF-8''%e2%82%ac%20rates`](https://datatracker.ietf.org/doc/html/rfc6266#section-5))

it also adds a cause to errors that gives a little more information rather than the bland "failed to parse form-data!" one

### CODE REVIEW

File: lib/web/fetch/formdata-parser.js [hunk 1]
```diff
@@ -290,34 +286,61 @@ function parseMultipartFormDataHeaders (input, position) {
...
+              )
+
+              if (
+                (headerValue[0] !== 0x75 && headerValue[0] !== 0x55) || // u or U
+                (headerValue[1] !== 0x74 && headerValue[1] !== 0x54) || // t or T
+                (headerValue[2] !== 0x66 && headerValue[2] !== 0x46) || // f or F
+                headerValue[3] !== 0x2d || // -
+                headerValue[4] !== 0x38 // 8
+              ) {
+                throw parsingError('unknown encoding, expected utf-8\'\'')
```
Comment (KhafraDev) [inline lib/web/fetch/formdata-parser.js:318]: I have no idea if `utf-8` is the only accepted value here. Could not find references to other encodings in the RFC.

**Review by metcoder95 — APPROVED** [review]
There are ways to cover this with test?

**Comment by KhafraDev** [comment]
I may have forgotten to commit the tests...

**Review by mcollina — APPROVED** [review]
lgtm
