### PR TITLE
test: handle npm ignore-scripts settings

### LINKED ISSUE #2287: Undici tests depend on install hooks
Adding the following lines to your `.npmrc` files will result in 5 test failures. 

```
ignore-scripts=true
```

Example failing test:

```
test/unix.js 2> Error: ENOENT: no such file or directory, open '/Users/yagiz/Developer/undici/node_modules/https-pem/key.pem'
test/unix.js 2>     at Object.openSync (node:fs:601:3)
test/unix.js 2>     at Object.readFileSync (node:fs:469:35)
test/unix.js 2>     at Object.<anonymous> (/Users/yagiz/Developer/undici/node_modules/https-pem/index.js:6:18)
test/unix.js 2>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
test/unix.js 2>     at Module._compile (/Users/yagiz/Developer/undici/node_modules/tap/node_modules/source-map-support/source-map-support.js:568:25)
test/unix.js 2>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
test/unix.js 2>     at Module.load (node:internal/modules/cjs/loader:1091:32)
test/unix.js 2>     at Function.Module._load (node:internal/modules/cjs/loader:938:12)
test/unix.js 2>     at Module.require (node:internal/modules/cjs/loader:1115:19)
test/unix.js 2>     at require (node:internal/modules/helpers:130:18)
```

PS: For security reasons, I think `undici` shouldn't rely on preinstall hooks.

cc @KhafraDev @ronag

### PR DESCRIPTION
**Pull request by panva**
Fixes #2287

### CODE REVIEW

**Review by metcoder95 — APPROVED** [review]

**Review by anonrig — APPROVED** [review]

File: scripts/generate-pem.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+/* istanbul ignore file */
+
+require('https-pem/install')
```
Comment (anonrig) [inline scripts/generate-pem.js:3]: Is it possible to run this only on environments that set ignore scripts command?

Comment (panva) [reply scripts/generate-pem.js:3]: How could we detect such environment? And is it worth investing into? It's not like this adds seconds of additional time to the test suite.

Comment (anonrig) [reply scripts/generate-pem.js:3]: You're right.

**Review by KhafraDev — APPROVED** [review]

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by KhafraDev** [comment]
btw @metcoder95 it looks like the fetch http2 tests are failing quite a bit

**Comment by metcoder95** [comment]
I'll take them a look for further PRs and maybe open an issue 👍
