### PR TITLE
better stack trace for body.json

### LINKED ISSUE #2212: Opaque, undebuggable stacktraces
## Bug Description

When calling `await r.json()`, if the request text was not valid JSON, undici returns an opaque stacktrace which does not go to the line where the error was happening. This makes debugging near impossible.

## Reproducible By

Write a fetch to an endpoint that does not return valid JSON. Then, call `fetch("/endpoint").then(r => r.json())`
## Expected Behavior

An error thrown on the line where `await request.json()` was called.

## Logs & Screenshots

Current behavior:
```
x-control-1      | SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON                                         
x-control-1      |     at JSON.parse (<anonymous>)                                                                              
x-control-1      |     at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)                                         
x-control-1      |     at successSteps (node:internal/deps/undici/undici:6636:27)                                               
x-control-1      |     at node:internal/deps/undici/undici:1236:60                                                              
x-control-1      |     at node:internal/process/task_queues:140:7                                                               
x-control-1      |     at AsyncResource.runInAsyncScope (node:async_hooks:206:9)                                                
x-control-1      |     at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)                                  
x-control-1      |     at processTicksAndRejections (node:internal/process/task_queues:95:5)    
```

## Environment

Node 20

### PR DESCRIPTION
**Pull request by KhafraDev**
fixes #2212 

I'm not totally thrilled with the solution, but it does fix the issue.

old stack trace is in the issue

new
```
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (\undici\lib\fetch\body.js:580:15)
    at successSteps (\undici\lib\fetch\body.js:520:23)
    at successSteps (\undici\lib\fetch\util.js:821:35)
    at fullyReadBody (\undici\lib\fetch\util.js:843:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (\undici\lib\fetch\body.js:535:3)
    at async /undici/test.mjs:3:1
```

### CODE REVIEW

File: lib/fetch/util.js [hunk 1]
```diff
@@ -837,7 +837,14 @@ function fullyReadBody (body, processBody, processBodyError) {
   }
 
   // 5. Read all bytes from reader, given successSteps and errorSteps.
-  readAllBytes(reader, successSteps, errorSteps)
+  try {
+    const result = await readAllBytes(reader)
+    await true
```
Comment (ronag) [inline lib/fetch/util.js:842]: I don't think these awaits are necessary?

Comment (KhafraDev) [reply lib/fetch/util.js:842]: it's to follow the spec by adding in a microtick https://github.com/nodejs/undici/issues/2212#issuecomment-1680859014

Comment (ronag) [reply lib/fetch/util.js:842]: Isn't there already a micro tick from the await above?

Comment (KhafraDev) [reply lib/fetch/util.js]: makes sense, removed them

**Review by ronag — APPROVED** [review]

File: lib/fetch/util.js [hunk 2]
```diff
@@ -812,17 +812,17 @@ function iteratorResult (pair, kind) {
...
  */
-function fullyReadBody (body, processBody, processBodyError) {
+async function fullyReadBody (body, processBody, processBodyError) {
   // 1. If taskDestination is null, then set taskDestination to
   //    the result of starting a new parallel queue.
 
   // 2. Let successSteps given a byte sequence bytes be to queue a
   //    fetch task to run processBody given bytes, with taskDestination.
-  const successSteps = (bytes) => queueMicrotask(() => processBody(bytes))
+  const successSteps = (bytes) => processBody(bytes)
```
Comment (mcollina) [inline lib/fetch/util.js:821]:
```suggestion
  const successSteps = processBody
```

File: lib/fetch/util.js [hunk 3]
```diff
@@ -812,17 +812,17 @@ function iteratorResult (pair, kind) {
...
 
   // 3. Let errorSteps be to queue a fetch task to run processBodyError,
   //    with taskDestination.
-  const errorSteps = (error) => queueMicrotask(() => processBodyError(error))
+  const errorSteps = (error) => processBodyError(error)
```
Comment (mcollina) [inline lib/fetch/util.js:825]:
```suggestion
  const errorSteps = processBodyError
```

**Review by mcollina — APPROVED** [review]
lgtm with a tiny suggestion to avoid creating two closures

**Review by metcoder95 — APPROVED** [review]
