### PR TITLE
Test WeakRef support

### LINKED ISSUE #501: WeakRef support
We should test that a `WeakRef`:d `Pool` or `Client` does not get garbage collected while there is an active socket.

So basically if the pool/client has no pending request and idle/keepalive timeout has expired it should be garbage collected, otherwise not.

I think this already works but needs a regression test.

`Client` has a ref to `Pool` through `onDrain` listener and `Socket` has a ref to `Client` through `[kClient]`.

I think sockets are GC roots so I believe they will never be GC:d while there is still an active connection.

### PR DESCRIPTION
**Pull request by dnlup**
Add a test to check [`WeakRef`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) support. 

I wasn't able to trigger the gc cycle any faster, I had to increase the default timeout of `tap`.

Fixes #501

### CODE REVIEW

File: test/gc.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    wrapper.request({
+      path: '/',
+      method: 'GET'
+    }, (err, { body }) => {
+      t.error(err)
+      body.once('end', () => {
+        clock.tick(600)
+      }).resume()
+    })
+  }
```
Comment (ronag) [inline test/gc.js:47]: Maybe something like:

```js

t.plan(3)

const weakRef = new WeakRef(client)
let disconnected = false

const registry = new FinalizationRegistry((name) => {
  t.strictEqual(disconnected, true)
  t.strictEqual(name, 'test')
  t.strictEqual(weakRef.deref(), undefined)
})

client.once('disconnect', () => {
  disconnected = true
})

registry.register(client, 'test')

wrapper.request({
  path: '/',
  method: 'GET'
}, (err, { body }) => {
  t.error(err)
  body.once('end', () => {
    clock.tick(600)
  }).resume()
})
```

Comment (dnlup) [reply test/gc.js:47]: It looks like it could be the fake clock

Comment (dnlup) [reply test/gc.js]: Manually spinning the fake clock seems to trigger a GC operation. The test is taking more than 10 seconds, though.

**Comment by mcollina** [comment]
Have you tried by exposing the gc and calling it?

**Comment by dnlup** [comment]
> Have you tried by exposing the gc and calling it?

Yes, but the thing that is making the difference seems to be the clock ticking. If I don't do this nothing happens, even if I trigger the `gc` manually.

File: test/gc.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+    t.strictEqual(weakRef.deref(), undefined)
+  })
+
+  server.listen(0, () => {
+    const client = new Client(`http://localhost:${server.address().port}`, {
+      keepAliveTimeoutThreshold: 500
+    })
+    client.once('disconnect', () => {
+      disconnected = true
+      clock.tick(1e6)
```
Comment (ronag) [inline test/gc.js:42]: Why is this tick needed?

Comment (dnlup) [reply test/gc.js:42]: This is the tick that allows for the `registry` callback to be called. Could it be that the fake clock interferes with the `gc` activity?

Comment (ronag) [reply test/gc.js:42]: Can you try without a fake clock?

Comment (dnlup) [reply test/gc.js:42]: The test remains stuck waiting for the callback without the tick, even if I call the `gc` manually. Maybe I'm missing something.

Comment (dnlup) [reply test/gc.js:42]: > Can you try without a fake clock?

Yes, let's try without the fake clock.

File: test/gc.js [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+/* global WeakRef, FinalizationRegistry */
+
+const { test } = require('tap')
+const { Client } = require('..')
+const { createServer } = require('net')
+const FakeTimers = require('@sinonjs/fake-timers')
+
+const SKIP = typeof WeakRef === 'undefined' || typeof FinalizationRegistry === 'undefined'
+
+test('gc should collect the client if there are no active sockets', { skip: SKIP }, t => {
```
Comment (ronag) [inline test/gc.js:11]: client if, and only if, there

File: test/gc.js (hunk 2 above)
Comment (dnlup) [reply test/gc.js]: Removed the fake clock and triggered `gc` manually. The timing is similar to before.

File: test/gc.js [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+    t.strictEqual(weakRef.deref(), undefined)
+  })
+
+  server.listen(0, () => {
+    const pool = new Pool(`http://localhost:${server.address().port}`, {
+      connections: 1,
+      keepAliveTimeoutThreshold: 500
+    })
+
+//    pool.once('disconnect', () => {
```
Comment (dnlup) [inline test/gc.js:83]: To test the same way we did for the `Client`, maybe the `Pool` should emit a `disconnect` event when all clients have disconnected, wdyt?

Comment (ronag) [reply test/gc.js:83]: I think pool should emit connect/disconnect with the client as first argument, i.e. simply forwarding the client events.

Comment (dnlup) [reply test/gc.js:83]: Ok. I think it would be better to open a separate issue/PR for this and then rebase the work we are doing here.

**Review by Ethan-Arrowood — APPROVED** [review]
lgtm - strange that its failing on one ci though

**Comment by dnlup** [comment]
> lgtm - strange that its failing on one ci though

I know 😢 . I can't test macOS locally, unfortunately. I want to be sure these tests are not flaky before merging, though.

**Comment by Ethan-Arrowood** [comment]
Just pulled locally - gc tests pass on my mac 😄

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ronag** [comment]
Unfortunately we can't merge this if the CI is flaky :/

**Comment by mcollina** [comment]
> Unfortunately we can't merge this if the CI is flaky :/. Could this be a GC bug?

Unfortunately CI is flaky independently of this. I would recommend landing.
