### PR TITLE
fix: content-disposition header parsing

### LINKED ISSUE #1903: `undici.request` parse header differently to `http.request`
## Bug Description

Header handling on `latin1` characters that do not have the same byte code in `utf8`.

## Reproducible By

HTTP proxy chaining provide a consistence behavior on `header` serialization.
```js
const http = require('http')

const header = 'attachment; filename="år.pdf"'
console.log(Buffer.from(header)) // <Buffer 61 74 74 61 63 68 6d 65 6e 74 3b 20 66 69 6c 65 6e 61 6d 65 3d 22 c3 a5 72 2e 70 64 66 22>

http.createServer(function(_, response) {
  response.writeHead(200, {
    'content-length': 2,
    'content-disposition': header
  })
  response.end('OK')
}).listen({ port: 6666 })

http.createServer(async function(_, response) {
  http.request('http://127.0.0.1:6666', {
    method: 'GET',
  }, function(res) {
    const { statusCode, headers } = res
    console.log(headers)
    console.log(Buffer.from(headers['content-disposition'])) // <Buffer 61 74 74 61 63 68 6d 65 6e 74 3b 20 66 69 6c 65 6e 61 6d 65 3d 22 c3 83 c2 a5 72 2e 70 64 66 22>
    delete headers['transfer-encoding']
    response.writeHead(statusCode, headers)
    res.pipe(response)
  }).end()
}).listen({ port: 7777 })

http.createServer(async function(_, response) {
  http.request('http://127.0.0.1:7777', {
    method: 'GET',
  }, function(res) {
    const { statusCode, headers } = res
    console.log(headers)
    console.log(Buffer.from(headers['content-disposition'])) // <Buffer 61 74 74 61 63 68 6d 65 6e 74 3b 20 66 69 6c 65 6e 61 6d 65 3d 22 c3 83 c2 a5 72 2e 70 64 66 22>
    delete headers['transfer-encoding']
    response.writeHead(statusCode, headers)
    res.pipe(response)
  }).end()
}).listen({ port: 8888 })
```

Undici proxy chaining is broken somehow for `å` character (the characters that is not match in byte in `latin1` and `utf8`)
```js
const http = require('http')
const { request } = require('undici')

const header = 'attachment; filename="år.pdf"'
console.log(Buffer.from(header)) // <Buffer 61 74 74 61 63 68 6d 65 6e 74 3b 20 66 69 6c 65 6e 61 6d 65 3d 22 c3 a5 72 2e 70 64 66 22>

http.createServer(function(_, response) {
  response.writeHead(200, {
    'content-length': 2,
    'content-disposition': header
  })
  response.end('OK')
}).listen({ port: 6666 })

http.createServer(async function(_, response) {
  const { statusCode, headers, body } = await request('http://localhost:6666', {
    method: "GET"
  })
  console.log(headers)
  console.log(Buffer.from(headers['content-disposition'])) // <Buffer 61 74 74 61 63 68 6d 65 6e 74 3b 20 66 69 6c 65 6e 61 6d 65 3d 22 c3 83 c2 a5 72 2e 70 64 66 22>
  delete headers['transfer-encoding']
  response.writeHead(statusCode, headers)
  body.pipe(response)
}).listen({ port: 7777 })

http.createServer(async function(_, response) {
  const { statusCode, headers, body } = await request('http://localhost:7777', {
    method: "GET"
  })
  console.log(headers)
  console.log(Buffer.from(headers['content-disposition'])) // <Buffer 61 74 74 61 63 68 6d 65 6e 74 3b 20 66 69 6c 65 6e 61 6d 65 3d 22 c3 a5 72 2e 70 64 66 22>
  delete headers['transfer-encoding']
  response.writeHead(statusCode, headers)
  body.pipe(response)
}).listen({ port: 8888 })
```

## Expected Behavior

I assume it is same as `http.request` or the bug is actually in `http`.

## Environment

Linux DESKTOP-S1RECSH 4.4.0-19041-Microsoft #2311-Microsoft Tue Nov 08 17:09:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux
Node.js v18.13.0

### Additional context

You can see more detail on the below issue.
Refs https://github.com/fastify/fastify-reply-from/issues/287

### PR DESCRIPTION
**Pull request by climba03003**
Fixes #1903 
I am not sure if it is good to mutate in `onHeaderValue`.

But I found it should be the most optimal place to do it.
Trans-code the header value in other place would result in heavy boating code.
For example, it would duplicate the logic if modify in `parseHeaders`.
https://github.com/nodejs/undici/blob/7827031d2a7fd99f8ab9d5eddce127c6f700dd35/lib/core/util.js#L212-L235

### CODE REVIEW

File: lib/client.js [hunk 1]
```diff
@@ -618,6 +619,11 @@ class Parser {
       this.connection += buf.toString()
     } else if (key.length === 14 && key.toString().toLowerCase() === 'content-length') {
       this.contentLength += buf.toString()
+    } else if (key.length === 19 && key.toString().toLowerCase() === 'content-disposition') {
+      // https://www.rfc-editor.org/rfc/rfc6266#section-4.3
+      // we need to recieve the buffer as latin1
+      // so it would not transform to utf-8 wrongly
+      this.headers[len - 1] = transcode(buf, 'latin1', 'utf8')
```
Comment (ronag) [inline lib/client.js:626]: Don't mutate :).

**Review by ronag — APPROVED** [review]

File: lib/client.js [hunk 2]
```diff
@@ -4,6 +4,7 @@
 
 const assert = require('assert')
 const net = require('net')
+const transcode = require('buffer').transcode
```
Comment (ronag) [inline lib/client.js:7]:
```suggestion
const Buffer = require('buffer')
```

File: lib/client.js (hunk 1 above)
Comment (ronag) [inline lib/client.js:626]:
```suggestion
      this.headers[len - 1] = Buffer.transcode(buf, 'latin1', 'utf8')
```

**Review by ronag — APPROVED** [review]

File: lib/client.js [hunk 3]
```diff
@@ -618,6 +619,11 @@ class Parser {
       this.connection += buf.toString()
     } else if (key.length === 14 && key.toString().toLowerCase() === 'content-length') {
       this.contentLength += buf.toString()
+    } else if (key.length === 19 && key.toString().toLowerCase() === 'content-disposition') {
+      // https://www.rfc-editor.org/rfc/rfc6266#section-4.3
+      // we need to recieve the buffer as latin1
+      // so it would not transform to utf-8 wrongly
+      this.headers[len - 1] = Buffer.transcode(buf, 'latin1', 'utf8')
```
Comment (ronag) [inline lib/client.js:626]: Actually this needs to happen somewhere else.

**Review by ronag — CHANGES_REQUESTED** [review]
You can't process headers in onHeaderValue as they might be incomplete. It needs to be done in onHeadersComplete

File: test/issue-1903.js [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+    })
+    header.push('attachment; filename="år.pdf"')
+    res.end('OK', spinup1.resolve)
+  })
+  t.teardown(server.close.bind(server))
+  server.listen(0, spinup1.resolve)
+
+  const proxy1 = createServer(async (req, res) => {
+    const { statusCode, headers, body } = await request(`http://localhost:${server.address().port}`, {
+      method: "GET"
```
Comment (ronag) [inline test/issue-1903.js:39]:
```suggestion
      method: 'GET'
```

File: test/issue-1903.js [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+    delete headers['transfer-encoding']
+    res.writeHead(statusCode, headers)
+    body.pipe(res)
+  })
+  t.teardown(proxy1.close.bind(proxy1))
+  proxy1.listen(0, spinup2.resolve)
+
+  const proxy2 = createServer(async (req, res) => {
+    const { statusCode, headers, body } = await request(`http://localhost:${proxy1.address().port}`, {
+      method: "GET"
```
Comment (ronag) [inline test/issue-1903.js:51]:
```suggestion
      method: 'GET'
```

File: test/issue-1903.js [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+    body.pipe(res)
+  })
+  t.teardown(proxy2.close.bind(proxy2))
+  proxy2.listen(0, spinup3.resolve)
+
+  // wait until all server spinup
+  await Promise.all([spinup1.promise, spinup2.promise, spinup3.promise])
+
+  const { statusCode, headers, body } = await request(`http://localhost:${proxy2.address().port}`, {
+    method: "GET"
```
Comment (ronag) [inline test/issue-1903.js:65]:
```suggestion
    method: 'GET'
```

File: test/issue-1903.js [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+  t.equal(await body.text(), 'OK')
+
+  // we check header
+  // must not be the same in first proxy
+  t.notSame(header[0], header[1])
+  // chaining always the same value
+  t.equal(header[1], header[2])
+  t.equal(header[2], header[3])
+})
+
```
Comment (ronag) [inline test/issue-1903.js:78]:
```suggestion
```

File: lib/client.js (hunk 3 above)
Comment (climba03003) [reply lib/client.js]: Updated to trans-code inside `onHeadersComplete`

File: lib/client.js [hunk 8]
```diff
@@ -4,6 +4,7 @@
 
 const assert = require('assert')
 const net = require('net')
+const { transcode } = require('buffer')
```
Comment (climba03003) [inline lib/client.js:7]: It is required to do in this way since the below code using the `Buffer` class.

**Review by ronag — COMMENTED** [review]
I helped out a little bit. Hope you don't mind.

File: lib/mock/mock-utils.js [hunk 9]
```diff
@@ -188,7 +188,11 @@ function buildKey (opts) {
 }
 
 function generateKeyValues (data) {
-  return Object.entries(data).reduce((keyValuePairs, [key, value]) => [...keyValuePairs, key, value], [])
+  return Object.entries(data).reduce((keyValuePairs, [key, value]) => [
+    ...keyValuePairs,
+    Buffer.from(`${key}`),
+    Array.isArray(value) ? value.map(x => Buffer.from(`${x}`)) : Buffer.from(`${value}`)
+  ], [])
```
Comment (ronag) [inline lib/mock/mock-utils.js:195]: @mcollina

File: test/issue-1903.js [hunk 10]
```diff
@@ -0,0 +1,77 @@
+'use strict'
+
+const { createServer } = require('node:http')
```
Comment (climba03003) [inline test/issue-1903.js:3]:
```suggestion
const { createServer } = require('http')
```

File: lib/mock/mock-utils.js (hunk 9 above)
Comment (KhafraDev) [reply lib/mock/mock-utils.js:195]: This change is fine. It's used for parsing a headers object (key : string) to an array which is what `onHeaders` and `onComplete` expect (which is where this is used).

**Review by KhafraDev — APPROVED** [review]
