### PR TITLE
fix: handle invalid HTTP/2 connection headers (#4356)

### LINKED ISSUE #4356: Invalid HTTP2 headers should be recoverable
## Bug Description

If an invalid HTTP2 header is sent by the server, the client should be able to recover by retrying the operation.  See https://github.com/nodejs/undici/discussions/4341 for more details.

## Reproducible By

To reproduce, a mock reply will need to be constructed where an HTTP2 connection to a server gets a response with an HTTP1 header like "http2-settings".  

Ideally a runtime error is thrown, which can be caught in a block where Undici can be directed to retry the operation with a new connection.

## Environment

This was encountered using Node.js 22 on RHEL9.

### PR DESCRIPTION
**Pull request by mcollina**
## Summary

- catch `ERR_HTTP2_INVALID_CONNECTION_HEADERS` from `session.request()` in the HTTP/2 client
- wrap the Node.js error in `InformationalError` and preserve the original error as `cause`
- tear down the broken HTTP/2 session so queued requests can continue on a fresh connection
- add an HTTP/2 regression test covering both catchable failure and queue recovery

Fixes #4356

## Testing

- `npx eslint lib/core/errors.js lib/dispatcher/client-h2.js test/http2-invalid-connection-headers.js`
- `npx borp -p "test/http2-invalid-connection-headers.js"`
- `npm run test:h2:core`
- `npm run test:h2:fetch`

### CODE REVIEW

**Review by metcoder95 — APPROVED** [review]

File: lib/dispatcher/client-h2.js [hunk 1]
```diff
@@ -489,6 +491,26 @@ function writeH2 (client, request) {
     util.destroy(body, err)
   }
 
+  const requestStream = (headers, options) => {
+    try {
+      return session.request(headers, options)
+    } catch (err) {
+      if (err?.code !== 'ERR_HTTP2_INVALID_CONNECTION_HEADERS') {
+        throw err
+      }
```
Comment (webcarrot) [inline lib/dispatcher/client-h2.js:500]: @mcollina how users will be able to catch non `ERR_HTTP2_INVALID_CONNECTION_HEADERS` errors in context of https://github.com/nodejs/undici/issues/4356 ?
