### PR TITLE
fix: support Connection header with connection-specific header names per RFC 7230

### LINKED ISSUE #4774: Support sending Connection header with connection-specific header names per RFC 7230
## Summary

When using undici to make HTTP requests, attempting to send a `Connection` header with a value that lists other header names (per RFC 7230 Section 6.1) results in an `InvalidArgumentError: invalid connection header`.

## Background

RFC 7230 Section 6.1 specifies that the Connection header field can contain a comma-separated list of connection-option tokens, which correspond to header field names that should be removed by the first proxy or gateway that receives the message.

> The "Connection" header field allows the sender to indicate desired control options for the current connection. In order to avoid confusing downstream recipients, a proxy or gateway MUST remove or replace any received connection options before forwarding the message.

Example from the RFC:
```
Connection: close
Connection: keep-alive, Upgrade
Connection: X-Custom-Header
```

## Current Behavior

```javascript
const { request } = require('undici');

await request('http://example.com', {
  headers: {
    'X-Custom-Header': 'some-value',
    'Connection': 'X-Custom-Header'  // RFC-compliant header value
  }
});
// Throws: InvalidArgumentError: invalid connection header
```

## Expected Behavior

Undici should allow Connection header values that contain comma-separated lists of header names, per RFC 7230 Section 6.1.

## Use Case

This is relevant for proxy implementations where a client sends a Connection header listing custom headers to strip. While undici/proxies should strip these headers before forwarding (as we now do in @fastify/reply-from), the current undici behavior prevents clients from sending RFC-compliant requests in the first place.

## References

- [RFC 7230 Section 6.1 - Connection](https://datatracker.ietf.org/doc/html/rfc7230#section-6.1)
- Related fix in @fastify/reply-from: https://github.com/fastify/fastify-reply-from/issues/449

### PR DESCRIPTION
**Pull request by mcollina**
## Summary

- Allows Connection header to contain comma-separated list of connection option tokens (header names) per RFC 7230 Section 6.1
- Previously only `close` or `keep-alive` were accepted, now any valid HTTP token is allowed
- Sets `request.reset = true` if `close` is present in the token list

## Test plan

- [x] Added tests for `close` and `keep-alive` values
- [x] Added test for custom header name as connection option
- [x] Added test for comma-separated list of connection options
- [x] Added test for rejecting invalid tokens
- [x] All existing tests pass

Fixes #4774

### CODE REVIEW

File: lib/core/request.js [hunk 1]
```diff
@@ -394,12 +394,21 @@ function processHeader (request, key, val) {
...
-    if (value !== 'close' && value !== 'keep-alive') {
+    // Per RFC 7230 Section 6.1, Connection header can contain
+    // a comma-separated list of connection option tokens (header names)
+    const value = typeof val === 'string' ? val : null
+    if (value === null) {
       throw new InvalidArgumentError('invalid connection header')
     }
 
-    if (value === 'close') {
+    const tokens = value.split(',').map(t => t.trim().toLowerCase())
```
Comment (metcoder95) [inline lib/core/request.js]: We are iterating over them twice, can we do it at one pass?

Comment (Uzlopak) [reply lib/core/request.js]: You could actually lowercase before split.

Comment (mcollina) [reply lib/core/request.js]: Done! Refactored to lowercase before split and combined validation + close-check in a single loop.

**Comment by mcollina** [comment]
@metcoder95 ping
