### PR TITLE
fix(benchmarks): fix timeout errors

### LINKED ISSUE #456: Missing results on benchmarks in Node 10 and 12
Hi :wave: :smile: 

I am getting timeout errors when running benchmarks on Node 12 and 10, resulting in a premature exit without results. This doesn't happen on Node 14. Switching to the use of the `finish` event instead of `close` fixes this issue. Is this behavior wanted?

### PR DESCRIPTION
**Pull request by dnlup**
The use of `close` event was causing timeouts. Switching to the `finish` event fixed it.

Fixes #456

### CODE REVIEW

File: benchmarks/index.js [hunk 1]
```diff
@@ -37,6 +37,16 @@ client.on('disconnect', (err) => {
...
+// http.get(httpOptions, (res) => {
+//   res
+//     .pipe(new Writable({
+//       write (chunk, encoding, callback) {
+//         console.log(`${chunk}`)
+//         callback()
+//       }
+//     }))
+//     .on('finish', () => console.log('done'))
+// })
```
Comment (mcollina) [inline benchmarks/index.js:49]: Why this is here?

**Review by mcollina — COMMENTED** [review]
Are these running well on all versions of Node.js now?

File: benchmarks/index.js (hunk 1 above)
Comment (dnlup) [reply benchmarks/index.js:49]: Sorry, I removed it. It was trash I forgot to remove.

**Comment by dnlup** [comment]
> Are these running well on all versions of Node.js now?

No, I think we should add the matrix. If you agree I'll work on it.

**Comment by dnlup** [comment]
> Are these running well on all versions of Node.js now?

Sorry, I misunderstood. Yes, they run well on 10, 12, and 14. Do we want to add a matrix for benchmarks too?

**Comment by dnlup** [comment]
Maybe the same matrix used in tests. I am not sure if it might be too much.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm
