### PR TITLE
fix data url test

### LINKED ISSUE #2579: fetch: data url test fails
Caused by: de7dc7fabbbf7b97edb583b99003cb2222d4166f

```js
const { fetch } = require('./')
const assert = require('assert')

const input = "data:  ;charset=x   ;  base64,WA"
const expectedMimeType = "text/plain;charset=x"
const expectedBody = [88]

fetch(input).then(res => {
  return res.arrayBuffer().then(body => {
    assert.deepEqual(new Uint8Array(body), new Uint8Array(expectedBody))
    assert.equal(res.headers.get("content-type"), expectedMimeType)
  })
})

```

@tsctx

### PR DESCRIPTION
**Pull request by KhafraDev**
Fixes #2579 

fix was easier than I expected, I just reverted the changes here for the most part.

### CODE REVIEW

File: lib/fetch/dataURL.js [hunk 1]
```diff
@@ -630,14 +630,18 @@ function isASCIIWhitespace (char) {
  * @param {boolean} [trailing=true]
  */
 function removeASCIIWhitespace (str, leading = true, trailing = true) {
-  let i = 0; let j = str.length
+  let lead = 0
+  let trail = str.length - 1
+
   if (leading) {
-    while (j > i && isASCIIWhitespace(str.charCodeAt(i))) --i
```
Comment (KhafraDev) [inline lib/fetch/dataURL.js:635]: so unless `str.length` was 0 this would always be true... and we're decrementing from i, which means if isASCIIWhitespace(...) was true, `i` would be negative? Not sure why I didn't realize this before.

Comment (KhafraDev) [reply lib/fetch/dataURL.js:635]: also using `i` and `j` instead of `lead` and `trail` shouldn't have landed

**Review by mcollina — APPROVED** [review]
lgtm

File: lib/fetch/dataURL.js [hunk 2]
```diff
@@ -604,14 +604,18 @@ function isHTTPWhiteSpace (char) {
  * @param {boolean} [trailing=true]
  */
 function removeHTTPWhitespace (str, leading = true, trailing = true) {
-  let i = 0; let j = str.length
+  let lead = 0
+  let trail = str.length - 1
+
   if (leading) {
-    while (j > i && isHTTPWhiteSpace(str.charCodeAt(i))) --i
+    while (lead < str.length && isHTTPWhiteSpace(str.charCodeAt(lead))) lead++
```
Comment (tsctx) [inline lib/fetch/dataURL.js:611]: It may be better to save the length.

File: lib/fetch/dataURL.js [hunk 3]
```diff
@@ -630,14 +634,18 @@ function isASCIIWhitespace (char) {
  * @param {boolean} [trailing=true]
  */
 function removeASCIIWhitespace (str, leading = true, trailing = true) {
-  let i = 0; let j = str.length
+  let lead = 0
+  let trail = str.length - 1
+
   if (leading) {
-    while (j > i && isASCIIWhitespace(str.charCodeAt(i))) --i
+    while (lead < str.length && isASCIIWhitespace(str.charCodeAt(lead))) lead++
```
Comment (tsctx) [inline lib/fetch/dataURL.js:641]: same here

File: lib/fetch/dataURL.js (hunk 2 above)
Comment (KhafraDev) [reply lib/fetch/dataURL.js:611]: this code is very rarely run twice, it'd be a very pointless optimization (as in, I don't think I've ever seen a library or whatever put whitespaces in data urls).
