### PR TITLE
test: fix flaky debug test

### LINKED ISSUE #2600: test/debug.js is flaky :(
```
# Subtest: test/debug.js
    # Subtest: debug\#websocket
    ok 1 - debug\#websocket
      ---
      duration_ms: 692.207053
      ...
    # Subtest: debug\#fetch
    ok 2 - debug\#fetch
      ---
      duration_ms: 807.024345
      ...
    # Subtest: debug\#undici
    not ok 3 - debug\#undici
      ---
      duration_ms: 965.181717
      location: '/home/runner/work/undici/undici/test/debug.js:65:1'
      failureType: 'hookFailed'
      error: 'The plan was not completed'
      code: 'ERR_ASSERTION'
      name: 'AssertionError'
      expected: 10
      actual: 8
      operator: 'strictEqual'
      stack: |-
        TestContext.autoEnd (/home/runner/work/undici/undici/node_modules/@matteo.collina/tspl/tspl.js:25:14)
        TestHook.runInAsyncScope (node:async_hooks:203:9)
        TestHook.run (node:internal/test_runner/test:631:25)
        TestHook.run (node:internal/test_runner/test:856:18)
        TestHook.run (node:internal/util:530:12)
        node:internal/test_runner/test:565:20
        process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        async node:internal/test_runner/test:564:9
        async Test.runHook (node:internal/test_runner/test:563:7)
        async after (node:internal/test_runner/test:591:9)
      ...
    1..3
    # tests 3
    # suites 0
    # pass 2
    # fail 1
    # cancelled 0
    # skipped 0
    # todo 0
    # duration_ms 2472.022223
    # failed 1 of 3 tests
not ok 27 - test/debug.js # time=2811.968ms
  ---
  env: {}
  file: test/debug.js
  timeout: 60000
  command: /opt/hostedtoolcache/node/18.19.0/x64/bin/node
  args:
    - --expose-gc
    - test/debug.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/runner/work/undici/undici
  exitCode: 1
  ...
```

cc @metcoder95

### PR DESCRIPTION
**Pull request by metcoder95**
## This relates to...

Hopefully closes #2600 

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by metcoder95** [comment]
I think I've figured out what's the problem; it seems that sometimes we are resolving the promise faster than the time the data gets passed from the buffer.

I'll work on this later on but I'm focusing on a way to delay the test until the data has been processed fully on

File: test/fixtures/fetch.js [hunk 1]
```diff
@@ -1,6 +1,20 @@
...
+  res.end('hello world')
+})
+
+server.listen(0, () => {
+  const { port, address, family } = server.address()
+  const hostname = family === 'IPv6' ? `[${address}]` : address
+  fetch(`http://${hostname}:${port}`)
+    .then(
+      res => res.body.cancel(),
+      () => {}
```
Comment (metcoder95) [inline test/fixtures/fetch.js:15]:
```suggestion
      res => res.body.cancel()
```

**Review by mcollina — APPROVED** [review]
lgtm
