### PR TITLE
fix: accept URL origin in Agent

### LINKED ISSUE #889: Agent.dispatch should allow URL origin
Right now only `string` works but the type definitions say that `URL` is also supported.

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #889

```
szm@solus ~/Desktop/undici $ node benchmarks/benchmark.js 
│ Tests               │ Samples │           Result │ Tolerance │ Difference with slowest │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ http - no keepalive │      60 │  5837.63 req/sec │  ± 2.88 % │                       - │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ http - keepalive    │      15 │  9187.24 req/sec │  ± 2.44 % │               + 57.38 % │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ undici - pipeline   │      25 │ 13515.93 req/sec │  ± 2.76 % │              + 131.53 % │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ undici - request    │      10 │ 18800.16 req/sec │  ± 2.41 % │              + 222.05 % │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ undici - stream     │      20 │ 20052.72 req/sec │  ± 2.55 % │              + 243.51 % │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ undici - dispatch   │      10 │ 22855.44 req/sec │  ± 2.85 % │              + 291.52 % │
```

### CODE REVIEW

**Comment by szmarczak** [comment]
I wonder if it would be better to use `options.protocol`, `options.host` and `options.port` instead of `options.origin`. That way we don't have to use `new URL(...)` again.

**Comment by szmarczak** [comment]
https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/client.js#L161

is unsafe because:
https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/core/util.js#L75-L76

https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/core/util.js#L58-L72

meaning: it does not return `new URL(...)` if the we pass a `URL` instance. So the mutations are visible while they shouldn't be. What should we do?

**Comment by ronag** [comment]
> https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/client.js#L161
> 
> is unsafe because:
> https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/core/util.js#L75-L76
> 
> https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/core/util.js#L58-L72
> 
> meaning: it does not return `new URL(...)` if the we pass a `URL` instance. So the mutations are visible while they shouldn't be. What shall we do?

Make `parseURL` always copy?

File: lib/agent.js [hunk 1]
```diff
@@ -104,9 +104,7 @@ class Agent extends Dispatcher {
         throw new InvalidArgumentError('opts must be a object.')
       }
 
-      if (typeof opts.origin !== 'string' || opts.origin === '') {
-        throw new InvalidArgumentError('opts.origin must be a non-empty string.')
-      }
+      const { origin } = util.parseOrigin(opts.origin)
```
Comment (ronag) [inline lib/agent.js:107]: I'm a little concerned about the performance implications. Is it negligable?

**Review by ronag — APPROVED** [review]

**Comment by ronag** [comment]
> Fixes #889
> 
> ```
> szm@solus ~/Desktop/undici $ node benchmarks/benchmark.js 
> │ Tests               │ Samples │           Result │ Tolerance │ Difference with slowest │
> |─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
> │ http - no keepalive │      60 │  5837.63 req/sec │  ± 2.88 % │                       - │
> |─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
> │ http - keepalive    │      15 │  9187.24 req/sec │  ± 2.44 % │               + 57.38 % │
> |─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
> │ undici - pipeline   │      25 │ 13515.93 req/sec │  ± 2.76 % │              + 131.53 % │
> |─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
> │ undici - request    │      10 │ 18800.16 req/sec │  ± 2.41 % │              + 222.05 % │
> |─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
> │ undici - stream     │      20 │ 20052.72 req/sec │  ± 2.55 % │              + 243.51 % │
> |─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
> │ undici - dispatch   │      10 │ 22855.44 req/sec │  ± 2.85 % │              + 291.52 % │
> ```

Would be great if you did before/after.

**Comment by ronag** [comment]
> I wonder if it would be better to use `options.protocol`, `options.host` and `options.port` instead of `options.origin`. That way we don't have to use `new URL(...)` again.

You could let `origin` be an object with those properties...

File: lib/agent.js (hunk 1 above)
Comment (mcollina) [reply lib/agent.js:107]: Parsing URLs is _slow_, we should not be creating a fresh `URL` instance every time if possible.

Comment (ronag) [reply lib/agent.js:107]: origin is just used as a key here so we won't actually need to validate it.

Comment (ronag) [reply lib/agent.js:107]:
```
let origin
if (opts.origin && typeof opts.origin === 'string') {
  origin = opts.origin
} else if (opts.origin instanceof URL) {
  origin = opts.origin.origin
} else {
  throw new InvalidArgumentError('opts.origin must be a non-empty string or URL.')
}
```

**Review by mcollina — APPROVED** [review]
lgtm
