### PR TITLE
fix(fetch): handle URL credentials in dispatch path extraction

### LINKED ISSUE #4889: url.href.slice(url.origin.length) path extraction breaks when URL contains credentials
## Bug Description

PR #4837 changed the path extraction in `httpNetworkFetch`'s internal `dispatch()` from `url.pathname + url.search` to `url.href.slice(url.origin.length, ...)`. This is wrong when the URL contains credentials, because `url.origin` omits the userinfo component but `url.href` includes it:

```js
const url = new URL("http://user:pass@127.0.0.1:1234/path");
url.href.slice(url.origin.length); // ":pass@127.0.0.1:1234/path" ΓÇö should be "/path"
```

The garbled path fails the `path must be an absolute URL or start with a slash` check in `lib/core/request.js`, so the request never reaches the server.

## Reproducible By

<details>
<summary>Run this script with undici 7.23.0+</summary>

```js
const http = require("http");
const crypto = require("crypto");
const { WebSocket } = require("undici");

const server = http.createServer();

server.on("upgrade", (req, socket) => {
  console.log("Server received upgrade request:");
  console.log("  URL:", req.url);
  console.log("  Authorization:", req.headers.authorization || "(none)");

  const auth = req.headers.authorization;
  if (!auth || auth !== "Basic " + Buffer.from("user:pass").toString("base64")) {
    socket.write(
      "HTTP/1.1 401 Unauthorized\r\n" +
      "WWW-Authenticate: Basic realm=\"test\"\r\n" +
      "Content-Length: 0\r\n" +
      "\r\n"
    );
    socket.destroy();
    return;
  }

  const key = req.headers["sec-websocket-key"];
  const accept = crypto
    .createHash("sha1")
    .update(key + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11")
    .digest("base64");

  socket.write(
    "HTTP/1.1 101 Switching Protocols\r\n" +
    "Upgrade: websocket\r\n" +
    "Connection: Upgrade\r\n" +
    "Sec-WebSocket-Accept: " + accept + "\r\n" +
    "\r\n"
  );
});

server.listen(0, "127.0.0.1", () => {
  const { port } = server.address();
  const url = "ws://user:pass@127.0.0.1:" + port + "/path";
  console.log("Connecting to " + url);

  const ws = new WebSocket(url);

  const timeout = setTimeout(() => {
    console.log("FAIL: Timed out");
    server.close();
    process.exitCode = 1;
  }, 5000);

  ws.addEventListener("open", () => {
    console.log("PASS: WebSocket opened successfully");
    clearTimeout(timeout);
    ws.close();
    server.close();
  });

  ws.addEventListener("error", e => {
    console.log("FAIL: WebSocket error:", e.error);
    clearTimeout(timeout);
    server.close();
    process.exitCode = 1;
  });
});
```

</details>

## Expected Behavior

The WebSocket connects successfully via the 401 challenge-response flow: first request without credentials gets a 401, retry with `Authorization` header succeeds. This works on 7.22.0.

## Environment

Windows 11 (ARM64), Node v25.5.0, undici 7.24.0

### Additional context

This breaks WebSocket basic auth (the `useURLCredentials` / 401 challenge-response flow), since the request URL retains credentials throughout.

### PR DESCRIPTION
**Pull request by mcollina**
## Summary
- fix fetch dispatch path extraction for URLs that include credentials
- preserve the trailing `?` behavior introduced in #4837
- add a websocket regression test for the 401 challenge/response flow with URL credentials

## Details
Using `url.href.slice(url.origin.length)` breaks when userinfo is present (`user:pass@...`), because `origin` excludes credentials while `href` includes them. That produces an invalid path and prevents dispatch.

This change builds the path from `url.pathname + url.search` and explicitly preserves trailing `?` when present.

## Test plan
- `node --test test/websocket/issue-4889.js`
- `npx borp -p "test/fetch/issue-4836.js"`
- `npx eslint lib/web/fetch/index.js test/websocket/issue-4889.js`

Closes #4889.

### CODE REVIEW

**Comment by mcollina** [comment]
@KhafraDev @domenic can you urgently review this? I need to land asap, ship a minor to be included in the upcoming Node 24 security release

File: test/fetch/issue-4897.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    t.assert.strictEqual(err.cause?.message, 'stop')
+    return true
+  })
+}
+
+// https://github.com/nodejs/undici/issues/4897
+test('fetch path extraction does not match hostnames inside scheme', async (t) => {
+  const hosts = ['h', 't', 'p', 'ht', 'tp', 'tt']
+
+  for (const scheme of ['http', 'https']) {
```
Comment (domenic) [inline test/fetch/issue-4897.js:29]: You could add `for (const userinfo of ['', 'user:pass@'])` and then update the URL to `${scheme}://${userinfo}${host}/test?a=b#frag` for extra coverage.

File: test/websocket/issue-4889.js
Comment (domenic) [inline test/websocket/issue-4889.js:1]: Not sure I understand the motivation behind changing this file.

**Review by domenic — APPROVED** [review]
Code LGTM, left some nits on the tests

**Review by KhafraDev — APPROVED** [review]

File: lib/web/fetch/index.js [hunk 2]
```diff
@@ -2132,9 +2132,12 @@ async function httpNetworkFetch (
     /** @type {import('../../..').Agent} */
     const agent = fetchParams.controller.dispatcher
 
+    const path = url.pathname + url.search
+    const hasTrailingQuestionMark = url.search.length === 0 && url.href[url.href.length - url.hash.length - 1] === '?'
```
Comment (PandaWorker) [inline lib/web/fetch/index.js]: a case that is not being processed

new URL('https://http/api?#') // '/api'
