### PR TITLE
fix: error stream instead of canceling

### LINKED ISSUE #4799: Cloning Response change default aborting behavior
## Bug Description

When using an AbortSignal with fetch, and aborting it right before reading the body via `text()`/`json()`/..., it throws an abort error, as expected.

But if the response was cloned, then it does not throw an abort error but a TypeError, like if the body was read by someone.

## Reproducible By

```js
async function test() {
  try {
    const controller = new AbortController();
    const response = await fetch("https://example.com/data", {
      signal: controller.signal,
    });
    const cloned_response = response.clone();
    controller.abort();
    // body is now used in the original response
    console.log("response.bodyUsed", response.bodyUsed);
    console.log("cloned_response.bodyUsed", cloned_response.bodyUsed);
    // throws "Body is unusable: Body has already been read"
    // but it should only throw an AbortError
    await response.text();
  } catch (error) {
    console.error(error);
  }

  console.log("--------------------------------");

  // this works as expected
  try {
    const controller = new AbortController();
    const response = await fetch("https://example.com/data", {
      signal: controller.signal,
    });
    // const cloned_response = response.clone();
    controller.abort();
    // throws AbortError as expected
    await response.text();
  } catch (error) {
    console.error(error);
  }
}

test();
```

```txt
response.bodyUsed true
cloned_response.bodyUsed false
TypeError: Body is unusable: Body has already been read
    at consumeBody (node:internal/deps/undici/undici:6873:31)
    at _Response.text (node:internal/deps/undici/undici:6821:18)
    at test (file:///.../reproduction.js:14:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
--------------------------------
DOMException [AbortError]: The operation was aborted.
    at new DOMException (node:internal/per_context/domexception:76:18)
    at consumeBody (node:internal/deps/undici/undici:6876:31)
    at _Response.text (node:internal/deps/undici/undici:6821:18)
    at test (file:///.../reproduction.js:31:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
```

## Expected Behavior

I expected it to throw an AbortError, exactly like the example without a cloned response.

## Environment

macOS 15.6.1
node 24.13.0

### PR DESCRIPTION
**Pull request by KhafraDev**
closes #4801
fixes #4799

### CODE REVIEW

File: test/fetch/issue-4799.js [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+
+  const clonedResponse = response.clone()
+
+  t.assert.strictEqual(response.bodyUsed, false)
+  t.assert.strictEqual(clonedResponse.bodyUsed, false)
+
+  controller.abort()
+
+  // Erroring a stream (see: https://fetch.spec.whatwg.org/#abort-fetch step 5) does not disturb it.
+  t.assert.strictEqual(response.bodyUsed, false)
```
Comment (KhafraDev) [inline test/fetch/issue-4799.js:107]: In #4801 Claude, for some reason, thought bodyUsed was true here. All of the other tests are unchanged.

File: lib/web/fetch/body.js [hunk 2]
```diff
@@ -422,18 +422,14 @@ function consumeBody (object, convertBytesToJSValue, instance, getInternalState)
...
+  object = getInternalState(object)
 
   // 1. If object is unusable, then return a promise rejected
   //    with a TypeError.
-  if (bodyUnusable(state)) {
+  if (bodyUnusable(object)) {
     return Promise.reject(new TypeError('Body is unusable: Body has already been read'))
   }
 
-  if (state.aborted) {
```
Comment (KhafraDev) [inline lib/web/fetch/body.js:433]: Image

I've wanted to remove this for years
