### PR TITLE
fix(parser): safer get_error_reason

### LINKED ISSUE #684: parser error reason reading is not safe
If execute e.g. returns `HPE_PAUSED` then the logic for reading the reason string goes crazy.

This can be reproduced by making `kOnBody` return `21` at the end and running `npm run test`.

```
Invalid EOF statePausedHPE_OKHPE_INTERNALHPE_STRICTHPE_LF_EXPECTEDHPE_UNEXPECTED_CONTENT_LENGTHHPE_CLOSED_CONNECTIONHPE_INVALID_METHODHPE_INVALID_URLHPE_INVALID_CONSTANTHPE_INVALID_VERSIONHPE_INVALID_HEADER_TOKENHPE_INVALID_CONTENT_LENGTHHPE_INVALID_CHUNK_SIZEHPE_INVALID_STATUSHPE_INVALID_EOF_STATEHPE_INVALID_TRANSFER_ENCODINGHPE_CB_MESSAGE_BEGINHPE_CB_HEADERS_COMPLETEHPE_CB_MESSAGE_COMPLETEHPE_CB_CHUNK_HEADERHPE_CB_CHUNK_COMPLETEHPE_PAUSEDHPE_PAUSED_UPGRADEHPE_USERDELETEGETHEADPOSTPUTCONNECTOPTIONSTRACECOPYLOCKMKCOLMOVEPROPFINDPROPPATCHSEARCHUNLOCKBINDREBINDUNBINDACLREPORTMKACTIVITYCHECKOUTMERGEM-SEARCHNOTIFYSUBSCRIBEUNSUBSCRIBEPATCHPURGEMKCALENDARLINKUNLINKSOURCEPRIDESCRIBEANNOUNCESETUPPLAYPAUSETEARDOWNGET_PARAMETERSET_PARAMETERREDIRECTRECORDFLUSHQXep������4K^t�����
                                                                                                                                                            (/38=AIQW\aglu����������������"+16<ESajqPause on CONNECT/Upgradeloseeep-aliveContent-Length overflowInvalid character in Content-Lengthchunked
                                                          
> 180 |       return new HTTPParserError(message, code)                                                          
```

### PR DESCRIPTION
**Pull request by dnlup**
Check that the returned pointer is valid befire retrieving the error
message.

Fixes #684

### CODE REVIEW

File: lib/client.js [hunk 1]
```diff
@@ -515,8 +515,13 @@ class Parser {
       socket.unshift(data.slice(offset))
     } else {
       const ptr = this.inst.llhttp_get_error_reason(this.ptr)
-      const len = new Uint8Array(this.inst.memory.buffer).indexOf(0, ptr) - ptr
-      const message = Buffer.from(this.inst.memory.buffer, ptr, len).toString()
+      let message
+      if (ptr !== 0) {
```
Comment (ronag) [inline lib/client.js:519]:
```suggestion
      if (!ptr) {
```

**Review by ronag — APPROVED** [review]
