### PR TITLE
fix: servername calculation

### LINKED ISSUE #992: Incorrect `servername` calculation
#1005

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #992

### CODE REVIEW

File: lib/core/util.js [hunk 1]
```diff
@@ -85,22 +85,17 @@ function getServerName (host) {
...
   }
 
-  if (net.isIP(servername)) {
-    servername = null
-  }
+  const idx = host.indexOf(':')
+  if (idx === -1) return host
 
-  return servername
+  return host.substr(0, idx)
```
Comment (szmarczak) [inline lib/core/util.js:98]: This is much faster than `host.split(':', 1)[0]`

**Review by ronag — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm
