### PR TITLE
fix: memory leak in Agent

### LINKED ISSUE #4424: Memory leak in Agent
## Bug Description

There is still a memory leak in `Agent`.

## Reproducible By

```javascript
const { Agent, fetch, setGlobalDispatcher } = require('undici');

const agent = new Agent({
  keepAliveMaxTimeout: 1000,
});
setGlobalDispatcher(agent);

globalThis.agent = agent;

async function main() {
  const rs = await Promise.all([
    fetch('http://www.example.com/123'),
    fetch('http://example.com/234'),
    fetch('https://www.example.com/345'),
    fetch('https://example.com/456'),
  ]);

  console.log('done')
  setTimeout(() => undefined, 1000000)
}

void main();
```

Run the script with `--inspect`. After 'done', inspect `agent[kClients]`. There will be 4 items in the map.

## Expected Behavior

All clients should have been destroyed.

## Logs & Screenshots

Image

## Environment

Undici 7.14.0, Nodejs 22.16.0.

### Additional context

In `Agent::[kDispatch]` the `key` of `this[kClients]` is a string, but in `Agent::[kOnConnect]` and `Agent::[kOnDisconnect]` the `origin` is a URL object. Even if it is coerced into a string, there will be a trailing slash which makes it different from the original key.

### PR DESCRIPTION
**Pull request by hexchain**
## This relates to...

#4424

## Changes

Instead of using `origin` from the `connect` and `disconnect` events, track client using the original key.

### Features

N/A

### Bug Fixes

#4424

### Breaking Changes and Deprecations

N/A

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md#developers-certificate-of-origin

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add a unit test?

**Comment by hexchain** [comment]
Added a unit test for the referenced issue.

File: lib/dispatcher/agent.js [hunk 1]
```diff
@@ -91,7 +79,23 @@ class Agent extends DispatcherBase {
     if (!dispatcher) {
       dispatcher = this[kFactory](opts.origin, this[kOptions])
         .on('drain', this[kOnDrain])
+        .on('connect', () => {
```
Comment (metcoder95) [inline lib/dispatcher/agent.js]: Why not reuse the same event handler?

Comment (hexchain) [reply lib/dispatcher/agent.js]: There was no particular reason. I've updated to just register one event handler, and call the original handler in the closure.

**Comment by mcollina** [comment]
There are relevant regressions

**Comment by hexchain** [comment]
I've pushed a new version to fix the tests. Some other changes worth noting:

- In `Agent`, `close` is now used instead of `destroy` after untracking a client
- `connectionError` events are also handled now

**Review by mcollina — APPROVED** [review]
lgtm on green CI
