### PR TITLE
fix(fetch): provide reason upon rejecting when redirected

### LINKED ISSUE #1509: Unknown cause error when fetch fails due to a redirect
## Bug Description

When you make a fetch request with the `redirect` option set to "error", upon receiving a redirect, fetch will throw an error with an undefined cause and simply saying "fetch failed"

## Reproducible By

```js
fetch("https://i.imgur.com/BLUyAX0.png", { redirect: "error" })
```

## Expected Behavior

The error is thrown with a more explicit reason such as "Unexpected redirect"

## Logs & Screenshots

image

## Environment

Windows 11, Node.js v18.4.0

### PR DESCRIPTION
**Pull request by ImRodry**
Fixes #1509. This is my first PR here so I'm not sure if I did the tests correctly or if this is the right approach to this issue. If it isn't, please comment suggesting how I should do it and I'll gladly change it :)

### CODE REVIEW

**Comment by ImRodry** [comment]
Seems like CI was already failing before my commit so I assume there’s nothing I can do about that ?

File: test/fetch/request.js [hunk 1]
```diff
@@ -268,6 +269,13 @@ test('undefined signal', t => {
   t.end()
 })
 
+test('error on redirect', async t => {
+  const errorCause = await fetch('http://nodejs.org/', { redirect: 'error' }).catch(e => e.cause)
```
Comment (KhafraDev) [inline test/fetch/request.js:273]: This shouldn't use an external url, should use a node http server instead (examples can be found in other tests).

Comment (ImRodry) [reply test/fetch/request.js:273]: The other tests all use invalid URLs and I need this one to be a valid one and to redirect somewhere else. I chose the nodejs website but it can be any website really, as long as we put HTTP instead of https. Any suggestions?

Comment (KhafraDev) [reply test/fetch/request.js:273]: The other tests don't depend on a valid url to work; the behavior of the nodejs site could change at any time to not redirect, or the CI or site could have connection issues.

```js
const server = createServer((req, res) => {
    res.statusCode = 302
    res.end()
})
// ...
```

There's examples elsewhere of how to setup node http servers elsewhere in the tests.

Comment (ImRodry) [reply test/fetch/request.js:273]: Thanks! I've followed the patterns on other tests and mine passes now with a custom server. Feel free to take a look again!

**Review by ronag — APPROVED** [review]
